### ISSUE TITLE
Node creation dialog does not respect the position for a group

### ISSUE THREAD

**Issue by johannessteu** [neos/neos-ui#1112]
This addition to your Settings.yaml should render the blog group between general (start) and structure (100). Right now it will be the last group in that dialog

```
Neos:
  Neos:
    nodeTypes:
      groups:
        blog:
          position: 20
          label: 'Some group'
          collapsed: true
```
