### ISSUE TITLE
Content Constraints on childNodes don't seem to work

### ISSUE THREAD

**Issue by DavidSporer** [neos/neos-ui#1135]
Hi,

I'm running neos-ui using dev-master and noticed that content constraints don't seem to work.
E.g. I have this Node Type definition (don't mind the bavarian titles, it's a special customer ;-) ):
```yaml
'My.Package:CarouselContainer':
  superTypes:
    'Neos.Neos:Content': true
  ui:
    label: 'Außen rum für Buidl'
    group: custom
    inlineEditable: TRUE
  properties:
    headline:
      type: string
      defaultValue: 'Überschrift do nei!'
      ui:
        label: 'Headline'
        inlineEditable: false
  childNodes:
    items:
      type: 'Neos.Neos:ContentCollection'
      constraints:
        nodeTypes:
          # only allow feature elements in this ContentCollection
          'My.Package:CarouselItem': true
          '*': false
```

If I use the old UI, it works exactly like expected:
![image](https://user-images.githubusercontent.com/1636571/31482774-e37fa382-af29-11e7-9aba-9faa9575f777.png)

In the new UI though, I just get a list of all Node Types that are available.
![image](https://user-images.githubusercontent.com/1636571/31482820-15112092-af2a-11e7-9265-89527fade810.png)

The only error I can see in the console is that this file is missing: 
_Resources/Static/Packages/Neos.Neos.Ui/Plugins/ckeditor/skins/minimalist/editor.css?t=H7HD
Please let me know if I can provide more info. Still don't know much about React or the new UI but I'd be happy to help.
