### ISSUE TITLE
Improve node creation dialog

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#1138]
- [x] Add possibility to set default values for editors in node creation dialog
- [x] Add some sort of grouping or layout. Right now the elements are too wide. See #3513
- [x] Make all editors work (e.g. those that need secondary inspector)

**Comment by dimaip** [comment]
I will work on this during the sprint (but would be great if somebody wants to share the efforts!)

**Comment by johannessteu** [comment]
I'll be at the sprint and don't got any specific topics for now but would like to work on React that week. So would be thankful to help on that and keep learning :)

**Comment by dimaip** [comment]
I would be thankful to have such cool company! Node creation dialog in combination with the node templates package is such a blast a can't describe!

**Comment by DrillSergeant** [comment]
Maybe we could add i18n-Labels for node creation dialog to the list?

**Comment by dimaip** [comment]
@DrillSergeant Uhm no, there's a ticket for that, we just need to provide fallbacks for that. That's super simple to tacke: basically search for all usages of I18n without fallbacks and add the English fallbacks.
Maybe you could give it a try?

**Comment by DrillSergeant** [comment]
@dimaip I was relating to the labels of dialog-elements:

```

    creationDialog:
      elements:
        date:
          type: DateTime
          ui:
            label: i18n
            editor: 'Neos.Neos/Inspector/Editors/DateTimeEditor'
            editorOptions:
              format: 'd.m.Y'
```

Shows like this:
![image](https://user-images.githubusercontent.com/883552/35048267-c86c8942-fb9c-11e7-90b8-abd250a1a623.png)

Not sure if mean the same type of labels.
