### ISSUE TITLE
Create an image node on image drop

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#1149]
We should support pasting/dropping images (and other media types) into Neos.
The problem is what type of node to create on paste?
I propose to introduce a config that would tell the UI what node to create based on media type.

E.g.:

```
Neos:
  Neos:
    Ui:
      dropTypes:
        image:
          dragType: 'image/jpeg'
          nodeType: 'Neos.Neos.NodeTypes:Image'
          nodeProperty: 'image'
```
