### ISSUE TITLE
Prototype-based page rendering causes an infinite loop for non-existing page prototypes

### ISSUE THREAD

**Issue by putzwasser** [neos/neos-ui#1201]
# Problem

Rendering a page using page prototypes (see manual section [Using a DefaultPage Prototype](http://neos.readthedocs.io/en/latest/HowTos/SelectingPageTemplate.html#using-a-defaultpage-prototype)) causes an infinite loop in the backend.

# Steps to reproduce

1. Override the `root` `Case` object to render pages using prototypes:
```
root {
	default {
		renderPath >
		type = ${q(node).property('_nodeType') + '.Document'}
	}
}
```
2. Add a document node type definition to the `NodeTypes.yaml` and _don't create a corresponding fusion prototype_:
```
'V.S:NoFusionPrototypePage':
  superTypes:
    'Neos.Neos:Document': true
  childNodes:
    main:
      type: 'Neos.Neos:ContentCollection'
  ui:
    label: 'Page without Prototype'
```
3. Create a document of that nodetype in the backend.

# Visual example

![infinie-loop](https://user-images.githubusercontent.com/26040044/32233444-ac0af344-be5a-11e7-87c9-8fb294e15e0a.gif)
