### ISSUE TITLE
ImageEditor does not respect the configured Features

### ISSUE THREAD

**Issue by johannessteu** [neos/neos-ui#1263]
Given this configuration:
```
'teaserImage'
  type: 'Neos\Media\Domain\Model\ImageInterface'
  ui:
    label: 'Teaser Image'
    inspector:
      group: 'document'
      editorOptions:
        features:
          crop: FALSE
```

As an editor i'd expect the crop function to be disabled. But it is still available.
