### ISSUE TITLE
DateTime Editor in Creation Dialog throws error

### ISSUE THREAD

**Issue by maya-shines** [neos/neos-ui#1320]
When I try to use the DateTime editor in my creation dialog, a JavaScript error is thrown.
This code:
```    
creationDialog:
  elements:
    title: ~
    issue:
      type: Date
      ui:
        label: 'Ausgabe'
        editor: 'Neos.Neos/Inspector/Editors/DateTimeEditor'
```
causes this output:
`TypeError: Cannot read property 'replace' of undefined`
![bildschirmfoto 2017-11-20 um 10 57 37](https://user-images.githubusercontent.com/6552092/33012619-cce5aa50-cde1-11e7-9251-e180487ff1ab.png)

**Comment by dimaip** [comment]
Related to: #1138 

Not for 1.0 obviously.

**Comment by DrillSergeant** [comment]
Maybe this works meanwhile (I am on version 1.0.4).

```
    creationDialog:
      elements:
        date:
          type: DateTime
          ui:
            label: 'Datum'
            editor: 'Neos.Neos/Inspector/Editors/DateTimeEditor'
            editorOptions:
              format: 'd.m.Y'
          validation:
            'Neos.Neos/Validation/NotEmptyValidator': []

```
This is working for me.

But;
For me the validation is not working. I can submit the dialog without entering a date. @dimaip , shall I open a new issue for that?
