### ISSUE TITLE
Improved Select editor

### ISSUE THREAD

**Issue by skurfuerst** [neos/neos-ui#1362]

**Comment by GerDner** [comment]
Hi guys, i think i found a bug here.

Basically i have content nodes on a site (articles). Each node has multiple references on node of nodetype 'document' (Tags).  When i focus different articles in the content view, the already assigned references does'nt load correctly in the inspector. The max references shown in the inspector is 1. Sometimes the title is not shown but only a loading text and a node uid.
The nodes are saved correctly, so i guess it's a problem in the state transition, when you select different articles.

<img width="313" alt="bildschirmfoto 2017-11-30 um 09 53 06" src="https://user-images.githubusercontent.com/2052212/33422022-6aeae6fa-d5b4-11e7-9dd0-16ee4d91856b.png">

i'm on '1.0.*@beta' and Neos '~3.2.0'.

Tag NodeType

```yaml
'Netzreich.Fww:Tag':
  superTypes:
    'Neos.NodeTypes:Page': true
  ui:
    label: 'Blog Tag'
    group: general
    title:
      type: string
```

Article NodeType (shortened)

```yaml
'Netzreich.Fww:News':
  superTypes:
    'Neos.Neos:Content': true
  ui:
    inlineEditable: true
    label: 'Artikel'
  properties:
    tags:
      type: references
      ui:
        label: Tags
        inspector:
          group: Artikel
          editorOptions:
            nodeTypes: ['Netzreich.Fww:Tag']
```
