### ISSUE TITLE
Crop feature with aspect ratio doesn't work

### ISSUE THREAD

**Issue by siggj** [neos/neos-ui#1386]
Hi guys !
The crop feature with aspect ratio doesn't work in the new ui.
I tried to switch to the old ui and it works.

**Comment by mstruebing** [comment]
Are you sure? Which version of the UI do you use?
If you aren't using the current master, could you please try to test it there? 
I can't reproduce it.

**Comment by siggj** [comment]
Thanks for the answer.
I use the current master yes.

So, this is my configuration for a property with type Neos\Media\Domain\Model\ImageInterface : 

```
properties:
  image:
    type: Neos\Media\Domain\Model\ImageInterface
    ui:
      label: 'Preview image'
      reloadIfChanged: true
      inspector:
        group: 'image'
        position: 50
        editorOptions:
          features:
            crop: TRUE
          crop:
            aspectRatio:
              locked:
                width: 265
                height: 190 
``` 

With the old UI, the radio works : 

![image](https://user-images.githubusercontent.com/526370/33703958-b0a9d676-db2a-11e7-934f-b510718528af.png)

But with the new UI, no ratio detected and cannot chose another aspect ratio in the select : 

![image](https://user-images.githubusercontent.com/526370/33703984-c981e72e-db2a-11e7-871e-dc9d07748c96.png)
