### ISSUE TITLE
Document `creationDialog` feature

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-ui#1469]
Since the react UI is officially released with Neos 3.3 LTS I wanted to try out the new `creationDialog` feature:

```yaml
'My.Package:Content.SomeNodeType':
  ui:
    // ....
    creationDialog:
      elements:
        'someLink':
          type: string
          ui:
            label: 'Link target'
            editor: 'Neos.Neos/Inspector/Editors/LinkEditor'
          validation:
            'Neos.Neos/Validation/NotEmptyValidator': []
        'someLabel':
          type: string
          ui:
            label: 'Label'
            editor: 'Neos.Neos/Inspector/Editors/TextFieldEditor'
          validation:
            'Neos.Neos/Validation/NotEmptyValidator': []
```

Somehow that doesn't work (wizard is displayed but the property values are ignored) and I can't find any documentation for this feature.
Besides it is missing from the `NodeTypes` schema, so that the above leads to a warning in the configuration module:
```
My.Package:Content.SomeNodeType.ui.creationDialog -> This property is not allowed here, check the spelling if you think it belongs here.
```
