### ISSUE TITLE
Page goes blank when entering text into property field with custom Regex validator

### ISSUE THREAD

**Issue by Benjamin-K** [neos/neos-ui#1483]
We added a custom validator to a property that is used for custom id output. 

![bildschirmfoto 2017-12-21 um 16 26 12](https://user-images.githubusercontent.com/3098031/34262559-06fd2a62-e66d-11e7-9a50-cff3ecdc89d1.png)

The NodeType-Configuration looks like this:

```yaml
'WM.StarterKit:IdMixin':
  abstract: true
  superTypes:
    'WM.StarterKit:DefaultGroup': true
  properties:
    id:
      type: string
      defaultValue: ''
      ui:
        label: i18n
        reloadIfChanged: true
        inspector:
          group: default
          position: 100
      validation:
        Neos.Neos/Validation/RegularExpressionValidator:
          regularExpression: '^([a-z][a-z0-9-_]*)?$/i'
```

Whenever something is typed into the field in the backend, the whole page gets blank white. The developer console shows some errors:

<img width="930" alt="bildschirmfoto 2017-12-21 um 16 33 56" src="https://user-images.githubusercontent.com/3098031/34262540-fb5d6f00-e66c-11e7-85cf-4e8c85b38474.png">
