### ISSUE TITLE
TextAreaEditor doesn't display validation errors

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-ui#1487]
If a property has a validation in the `yaml` file configured, the error message will not show up in the new UI. Like that the editors will have no clue, why they can't apply changes.

### Old UI:
<img width="322" alt="screenshot 2017-12-22 15 30 12" src="https://user-images.githubusercontent.com/4510166/34301479-0aac28b4-e72d-11e7-810e-7b0d0c175630.png">

### New UI
<img width="308" alt="screenshot 2017-12-22 15 28 27" src="https://user-images.githubusercontent.com/4510166/34301442-e3ad9f4a-e72c-11e7-9b75-88f8aa70090c.png">

**Comment by dimaip** [comment]
Can't verify. Could you provide a sample .yaml file?

**Comment by dimaip** [comment]
What I tested:

![image](https://user-images.githubusercontent.com/837032/34302145-b8dd2ce0-e740-11e7-8c4a-e6a7d80b943c.png)

**Comment by jonnitto** [comment]
For example: 
```
Foo.Bar:Element
  properties:
    sublineOverview:
      type: string
      ui:
        label: i18n
        reloadIfChanged: false
        inspector:
          group: story
          position: 100
          editor: Neos.Neos/Inspector/Editors/TextAreaEditor
      validation:
        'Neos.Neos/Validation/LabelValidator': true
```

In the urlPathSegement field it works, but on custom fields not
