### ISSUE TITLE
PluginView Editor not working

### ISSUE THREAD

**Issue by hhoechtl** [neos/neos-ui#1495]
Neos-UI compiled: 1.0.3
Neos: 3.3.2

I have 2 plugins:
```yaml
'Onedrop.Vendor:ItemSelection':
  superTypes:
    'Neos.Neos:Plugin': TRUE
  ui:
    label: i18n
    group: plugins
    icon: 'icon-building'
  options:
    pluginViews:
      'CheckoutView':
        label: 'Checkout View'
        controllerActions:
          'Onedrop\Vendor\Controller\CheckoutController': ['address', 'summary', 'finish', 'updateCustomer']
```

```yaml
'Onedrop.Vendor:Checkout':
  superTypes:
    'Neos.Neos:Plugin': TRUE
  ui:
    label: i18n
    group: plugins
    icon: 'icon-star'
    inspector:
      tabs:
        settings:
          label: i18n
          icon: 'icon-pencil'
      groups:
        settings:
          tab: settings
          label: i18n
          icon: 'icon-bar-chart'
  properties:
    sepaForm:
      type: Neos\Media\Domain\Model\ImageInterface
      ui:
        label: i18n
        reloadIfChanged: true
        help:
          message: i18n
        inspector:
          group: settings
      validation:
        'Neos.Neos/Validation/NotEmptyValidator':
```

When I try to place the pluginview in the new UI, I get the following error:

![image](https://user-images.githubusercontent.com/5076356/34376500-490960a0-eaec-11e7-90ee-9f157d3dc3e3.png)

Stack-trace:
```
TypeError: Cannot read property 'length' of undefined
    at PluginViewEditor.renderPlaceholder (Host.js?416256e0:14)
    at PluginViewEditor.render (Host.js?416256e0:14)

componentStack: 
    in PluginViewEditor
    in Connect(PluginViewEditor)
    in Neos(Connect(PluginViewEditor))
    in div
    in EditorEnvelope
    in Neos(EditorEnvelope)
   ...
```

The XMLHttpRequest `/neos/content/master-plugins` returned:
```
{"300d7a58-c358-4897-b808-6b52d96b2e2e":"\"Item Selection\" on page \"Item reservieren\""}
```
