### ISSUE TITLE
ReferenceEditor does not respect a `startingPoint`

### ISSUE THREAD

**Issue by johannessteu** [neos/neos-ui#1496]
Given this configuration:
```
    news:
      type: reference
      ui:
        reloadIfChanged: true
        inspector:
          editorOptions:
            nodeTypes:
              - 'Yeebase.t3nDe:Article'
            startingPoint: /articles
```

The startingPoint is not respected. Therefore the ReferenceEditor won't find any results
