### ISSUE TITLE
SelectorBoxEditor does not set choosen data-source value

### ISSUE THREAD

**Issue by DrNik** [neos/neos-ui#1536]
The dropdown of SelectorBoxEditor gets emptied out at either "apply" or "reload", when provisioned via data-source.
The node property gets stored with the choosen value correctly,  though.

Tested versions:

- Neos: 3.3.3
- Neos.UI: 1.0.4

Nicola

**Comment by DrillSergeant** [comment]
I can confirm this behaviour (same versions). Here is the yaml-definition of my field:
```    
    zoom:
      type: integer
      defaultValue: 14
      ui:
        label: i18n
        reloadIfChanged: TRUE
        inspector:
          group: map
          position: 30
          editor: Content/Inspector/Editors/SelectBoxEditor
          editorOptions:
            values:
              0:
                label: 'Auto'
              1:
                label: '1'
              2:
                label: '2'
```

**Comment by DrNik** [comment]
UPDATE: by chance I discovered that the SelectorBoxEditor to work wants strings, not integers.

Don't know if it is wanted or a bug but casting keys as string makes the selector work on both new and old ui (where I faced the same issue and where I could discover the "fix").

Nicola

**Comment by DrillSergeant** [comment]
@DrNik , you mean this should work?

```    
    zoom:
      type: integer
      defaultValue: 14
      ui:
        label: i18n
        reloadIfChanged: TRUE
        inspector:
          group: map
          position: 30
          editor: Content/Inspector/Editors/SelectBoxEditor
          editorOptions:
            values:
              '0':
                label: 'Auto'
              '1':
                label: '1'
              '2':
                label: '2'
```

Still the same behaviour on my side.
