### ISSUE TITLE
Node creation dialog element labels translation not working

### ISSUE THREAD

**Issue by DrillSergeant** [neos/neos-ui#1539]
Seems labels with value "i18n" are not translated. Instead "i18n" is used as a fixed value.

**Steps to reproduce:**
* Add configuration to a node that adds an element to the node creation dialog:
```

    creationDialog:
      elements:
        date:
          type: DateTime
          ui:
            label: i18n
            editor: 'Neos.Neos/Inspector/Editors/DateTimeEditor'
            editorOptions:
              format: 'd.m.Y'
```
* Create a node (of the type you just added the creation dialog element for)

**Expected result:**
I see the element in the dialog with a translated label (or at least the i18n-key as fallback if no translation  exists yet.

**Actual result:**
The string "i18n" is used as label:
![image](https://user-images.githubusercontent.com/883552/35051207-fb827d98-fba4-11e7-975d-79249c36cddd.png)
