### ISSUE TITLE
Missing support for Depending Properties

### ISSUE THREAD

**Issue by dfeyer** [neos/neos-ui#1568]
The React UI does not support Depending Properties:

http://neos.readthedocs.io/en/stable/CreatingASite/NodeTypes/DependingProperties.html

We should implement at least the support without Backward compatibility, the current solution is lower level Ember based, so i think no way to have keep the compatibility here. In the documentation it's clearly noticed that the current API is experimental, so I think it's fine to break the compatibility. 

Reported on slack by @kdambekalns see https://neos-project.slack.com/archives/C0U0KEGDQ/p1516656865000167

**Comment by dimaip** [comment]
With React, it's very simple to implement a declarative API, instead of a low-level imperative one like we did before.

I propose to pre-process nodetype definition in the following way: check if the value of a config begins with `UI_eval:` (or any other keyword, can't think of better one right now), if yes then `eval()` it, e.g.

```js
(nodeProperty, value, node) => value.indexOf('UI_eval') === 0 ? eval(value) : value
```

where `node` would be set to the current focused node, with transient values from inspector overlayed on top.

This would allow the following usage:

```
properties:
  serviceType:
    type: string
    ui:
      label: 'Service Type'
      inspector:
        group: product
        editor: 'Content/Inspector/Editors/SelectBoxEditor'
        editorOptions:
          allowEmpty: true
          placeholder: 'Service Type'
          dataSourceIdentifier: 'acme-servicetypes'
  contractType:
    type: string
    ui:
      label: 'Contract Type'
      # only render when serviceType property is set, also cast it to bool to prevent proptype errors
      disabled: 'UI_eval:node.properties.serviceType && true'
      inspector:
        group: product
        editor: 'Content/Inspector/Editors/SelectBoxEditor'
        editorOptions:
          allowEmpty: true
          placeholder: 'Contract Type'
          dataSourceIdentifier: 'acme-contracttypes'
          dataSourceAdditionalData:
            # use serviceType property as the search term
            searchTerm: 'UI_eval:node.properties.serviceType'
```

Should be trivial to implement.

Thoughts? Ideas? Suggestions?
