### ISSUE TITLE
SelectBoxEditor with option multiple scrambles selected values on update

### ISSUE THREAD

**Issue by lorenzulrich** [neos/neos-ui#1574]
### Steps to Reproduce

1. Create a select box with the multiple options and define some values:

```
    ageCategories:
      type: array
      ui:
        label: i18n
        inspector:
          group: offer
          editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
          editorOptions:
            multiple: true
            values:
              'kinder':
                label: 'Kinder'
              'jugendliche':
                label: 'Jugendliche'
              'erwachsene':
                label: 'Erwachsene'

```

2. Now, select one of the values. As soon as you click the "Apply" button, the selected value disappears (this is a side-issue, not the actual issue, since the value is saved nevertheless):

![neos-select-multiple-selected-disappears](https://user-images.githubusercontent.com/1816023/35323830-35dd9c12-00ef-11e8-81a0-c9f76935b44a.gif)

3. Use some Fusion code to render the value to the frontend. If you inspect this, you will see that the value is rendered correctly:

![image](https://user-images.githubusercontent.com/1816023/35323966-9dbd4008-00ef-11e8-9265-871897537c87.png)

4. Now, go back to the backend and select another value. You will notice again that the selected value disappears:

![image](https://user-images.githubusercontent.com/1816023/35324064-dd597e84-00ef-11e8-8a6d-394878f86d9a.png)

5. If you re-check the output in the frontend, you will see that the value initially select is now split with a comma by each character, while the second value is correct:

![image](https://user-images.githubusercontent.com/1816023/35324121-0ea7d06c-00f0-11e8-9844-6e27096a3799.png)

6. If you continue selecting new values, the older values are always "scrambled" a little more:

![image](https://user-images.githubusercontent.com/1816023/35324160-3399676e-00f0-11e8-8724-ab69f58a7cd7.png)

Neos: 3.3
UI: 1.0.4
