### ISSUE TITLE
Improve handling of dimension constraints in multi-dimension setups

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#1611]
Currently constraints are only correctly applied on first load. Once you change one dimension, the second one should be re-filtered according to selected dimension's constraints.

Could be tricky to implement, as possibly it would require a server request to find out allowed dimensions.
In the old UI this logic feels really off too.

## Steps to reproduce

Take a similar dimension config:

```
    contentDimensions:
      country:
        label: 'Country'
        icon: icon-language
        default: eng
        defaultPreset: eng
        presets:
          eng:
            label: 'England'
            values:
              - eng
            uriSegment: eng
          rus:
            label: 'Russia'
            values:
              - rus
            uriSegment: rus
      language:
        label: 'Neos.Demo:Main:contentDimensions.language'
        icon: icon-language
        default: en_US
        defaultPreset: en_US
        presets:
          all: null
          en_US:
            label: 'English (US)'
            values:
              - en_US
            uriSegment: en
          en_UK:
            label: 'English (UK)'
            values:
              - en_UK
              - en_US
            uriSegment: uk
          de:
            label: German
            values:
              - de
            uriSegment: de
            constraints:
              country:
                'rus': true
                '*': false
          fr:
            label: French
            values:
              - fr
            uriSegment: fr
          nl:
            label: Dutch
            values:
              - nl
              - de
            uriSegment: nl
          da:
            label: Danish
            values:
              - da
            uriSegment: da
          lv:
            label: Latvian
            values:
              - lv
            uriSegment: lv
```

2. Select England as country. "German" language will be correctly hidden, due to constraints.
3. Choose Russia as country. "German" language would still be hidden, unless you apply selection of Russia and reload the page.
