### ISSUE TITLE
Edit/Preview width larger than content canvas space should show scrollbars

### ISSUE THREAD

**Issue by hlubek** [neos/neos-ui#1642]
### Description

Responsive preview modes might want to include larger breakpoints that cannot be fully shown in the content canvas on smaller monitors. Currently if the width for a preview mode exceeds the space of the content canvas element, the iframe is clipped and cannot be scrolled.

### Steps to Reproduce

1. Add a width to the desktop preview mode

```
Neos:
  Neos:
    userInterface:
      editPreviewModes:
        desktop:
          position: 400
          width: 1280
```

2. Open the Neos backend, switch to "Desktop" preview mode and make window smaller than 1280

#### Expected behavior

As an editor I would expect to see scrollbars to scroll the content canvas if the window size is less than the needed size to show the content canvas with the desired width for a configured preview.

#### Actual behavior

The content canvas cannot be scrolled and the overflow is hidden.

### Affected Versions

Neos: 3.3.3
UI: 1.0.4
