### ISSUE TITLE
Inlineeditable page property causes toolbar to pop up

### ISSUE THREAD

**Issue by hhoechtl** [neos/neos-ui#1666]
### Description

We often use inlineeditable page properties to make fixed labels on the page editable. This worked with the old UI and has a different behavior in the new UI.

The new UI opens the content element toolbar which is not needed and doesn't make sense in that use-case.

![Inline editable](http://g.recordit.co/HN5ZKDhCDx.gif)

### Steps to Reproduce

Define an inlineeditable page property e.g.:
```yaml
'Onedrop.Customer:Frontpage':
  superTypes:
    'Neos.NodeTypes:Page': true
  ui:
    label: i18n
    icon: 'icon-globe'
    inlineEditable: true
  properties:
    infoBarTextHotline:
      type: string
      defaultValue: 'Störungshotline:'
      ui:
        inlineEditable: true
```

Try to make it editable either in Fluid or Fusion:

```fusion
page.body.infoBarTextHotline = ${q(site).property('infoBarTextHotline')}
```

```html
<neos:contentElement.wrap node="{site}">
    <span>
        <neos:contentElement.editable property="infoBarTextHotline" tag="strong"/>
    </span>
</neos:contentElement.wrap>
```

#### Expected behavior

Property should be inline editable without the toolbar.

### Affected Versions

Neos: 3.3.6

UI: 1.0.7
