### ISSUE TITLE
hideInMenu does not work in Content module

### ISSUE THREAD

**Issue by cvette** [neos/neos-ui#1699]
### Description

When setting `hideInMenu` to true on a submodule, the menu item is hidden in every module except the Neos content module.

### Steps to Reproduce

1. Specify the `hideInMenu` Setting for a submodule
```
Neos:
  modules:
    management:
      submodules:
        media:
          hideInMenu: true
```
2. Open the content module (your site)

#### Expected behavior

The submodule should not be shown in the menu.

#### Actual behavior

The submodule is shown in the Neos content module and hidden in every other backend module.

### Affected Versions

Neos: 3.3.8
UI: v1.0.8
