### ISSUE TITLE
Usability: Preview mode background should be grey

### ISSUE THREAD

**Issue by rolandschuetz** [neos/neos-ui#1700]
### Description

Most websites have a white background, a mobile preview mode now had a white iframe on a white background. The Neos background should b grey so that the borders of the preview are clear to recognize.

Even cooler would be custom background images to achieve an effect like this:
http://mobiletest.me/iphone_5_emulator/?u=http://neos.io

### Steps to Reproduce

use a smartphone preview mode like this:

```
Neos:
  Neos:
    userInterface:
      editPreviewModes:
        mobile:
          isEditingMode: false
          isPreviewMode: true
          fusionRenderingPath: ''
          title: 'Handy'
          width: 360px
          height: 640px
```

#### Expected behavior

I can see where my websie starts and ends in the preview.

#### Actual behavior

White iframe website background on white Neos background.
