### ISSUE TITLE
SelectBox not showing current value for integer properties

### ISSUE THREAD

**Issue by DrillSergeant** [neos/neos-ui#1704]
### Steps to Reproduce

1. create a node-property with this config
```
    zoom:
      type: integer
      defaultValue: ''
      ui:
        label: i18n
        reloadIfChanged: TRUE
        inspector:
          group: map
          position: 30
          editor: Content/Inspector/Editors/SelectBoxEditor
          editorOptions:
            values:
              0:
                label: 'Auto'
              1:
                label: '1'
              2:
                label: '2'
```

2. Go to the backend, select a value from the selectBox and click "apply"

#### Expected behavior
After reload of the document (reloadIfChanged is true) the selected value is shown in the editor.

#### Actual behavior
After reload of the document the editor is empty (there is no option selected).

The value is saved in db correctly, but it's not shown correctly in the UI. When I switch the property-type to "string" it works as expected.

Neos: 3.3.8
UI: 1.0.8
