### ISSUE TITLE
Loading fails if no node can be focused

### ISSUE THREAD

**Issue by ComiR** [neos/neos-ui#1725]
### Description
Without the permission to edit any node, the backend fails to load.
Legacy backend `/neos/legacy` works fine.

### Steps to Reproduce

1. `Policy.yaml` (includes privileges for legacy backend)
```yaml
privilegeTargets:
  Neos\Neos\Security\Authorization\Privilege\NodeTreePrivilege:
    'My.Package:Example':
      # I did not test this, but the goal is to show the homepage, but not anything else.
      # Especially editing content should not be possible
      matcher: !nodeIsOfType("Neos.Demo:Homepage")

roles:
  'My.Package:NewUser':
    privileges:
      -
        privilegeTarget: 'Neos.Neos:Backend.GeneralAccess'
        permission: GRANT
      -
        privilegeTarget: 'Neos.Neos.Ui:Backend.GeneralAccess'
        permission: GRANT
      -
        privilegeTarget: 'Neos.Neos.Ui:Backend.ServiceAccess'
        permission: GRANT
      -
        privilegeTarget: 'Neos.Neos:Backend.PersonalWorkspaceReadAccess.NodeConverter'
        permission: GRANT
      -
#        also needed to get unpublished content
        privilegeTarget: 'Neos.Neos:Backend.PublishOwnWorkspaceContent'
        permission: GRANT
      -
        privilegeTarget: 'Neos.Neos:Backend.DiscardOwnWorkspaceContent'
        permission: GRANT
      -
#        not only needed to edit content, but also to show it
        privilegeTarget: 'Neos.Neos:Backend.EditContent'
        permission: GRANT
      -
        privilegeTarget: 'Neos.Neos:Backend.ContentDimensions'
        permission: GRANT
      -
        privilegeTarget: 'Neos.Neos:Backend.EditUserPreferences'
        permission: GRANT
      -
        privilegeTarget: 'Neos.Neos:Backend.Module.Content'
        permission: GRANT
      -
        privilegeTarget: 'Neos.Neos:Backend.Module.User'
        permission: GRANT
      -
        privilegeTarget: 'Neos.Neos:Backend.Module.User.UserSettings'
        permission: GRANT
      -
        privilegeTarget: 'Neos.Neos:Backend.Module.User.UserSettings.UpdateOwnSettings'
        permission: GRANT
      -
        privilegeTarget: 'Neos.Neos:Backend.Module.Management'
        permission: GRANT
      -
        privilegeTarget: 'Neos.Neos:Backend.Module.Management.Workspaces'
        permission: GRANT
      -
        privilegeTarget: 'Neos.Neos:Backend.Service.Workspaces.Index'
        permission: GRANT
```
2. With an user only having the role `My.Package:NewUser` login
   * This will probably work (if cache was empty). If not, the same error will appear here already.
3. Navigate to a page through normal site navigation.

#### Expected behavior
Browsing through the site like in the frontend.

#### Actual behavior
Blank page. JS console output:
```
react-dom.production.min.js:164 Error: Key must be a string
    at NodeTypesRegistry.get (SynchronousRegistry.js:48)
    at NodeTypesRegistry.getInspectorViewConfigurationFor (NodeTypesRegistry.js:107)
    at Inspector.cloneViewConfiguration (index.js:101)
    at Inspector.componentWillReceiveProps (index.js:82)
    at updateClassInstance (react-dom.production.min.js:111)
    at beginWork (react-dom.production.min.js:133)
    at d (react-dom.production.min.js:161)
    at f (react-dom.production.min.js:161)
    at g (react-dom.production.min.js:162)
    at m (react-dom.production.min.js:169)
h @ react-dom.production.min.js:164
g @ react-dom.production.min.js:162
m @ react-dom.production.min.js:169
w @ react-dom.production.min.js:168
z @ react-dom.production.min.js:167
u @ react-dom.production.min.js:165
updateContainer @ react-dom.production.min.js:175
(anonymous) @ react-dom.production.min.js:225
unbatchedUpdates @ react-dom.production.min.js:171
Pg @ react-dom.production.min.js:225
unstable_renderSubtreeIntoContainer @ react-dom.production.min.js:227
Frame.n.renderFrameContents @ frame.js:83
(anonymous) @ VM1216 subpage@user-comir;language=de.html:1458

react-dom.production.min.js:164 TypeError: Cannot read property 'contentWindow' of undefined
    at getGuestFrameWindow (dom.js:20)
    at new NodeToolbar (index.js:51)
    at constructClassInstance (react-dom.production.min.js:109)
    at beginWork (react-dom.production.min.js:133)
    at d (react-dom.production.min.js:161)
    at f (react-dom.production.min.js:161)
    at g (react-dom.production.min.js:162)
    at m (react-dom.production.min.js:169)
    at w (react-dom.production.min.js:168)
    at z (react-dom.production.min.js:167)
h @ react-dom.production.min.js:164
g @ react-dom.production.min.js:162
m @ react-dom.production.min.js:169
w @ react-dom.production.min.js:168
z @ react-dom.production.min.js:167
u @ react-dom.production.min.js:165
updateContainer @ react-dom.production.min.js:175
(anonymous) @ react-dom.production.min.js:225
unbatchedUpdates @ react-dom.production.min.js:171
Pg @ react-dom.production.min.js:225
unstable_renderSubtreeIntoContainer @ react-dom.production.min.js:227
Frame.n.renderFrameContents @ frame.js:83
(anonymous) @ VM1216 subpage@user-comir;language=de.html:1458
```

### Affected Versions
Neos: 3.3.9
UI: 1.0.9
