### ISSUE TITLE
Labels of own modules are not rendered

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#1740]
### Description

If you create own backend modules and use local language labels instead of plain text, the label
will be not rendered with react-ui. You only get the label key, instead your not using the Neos.Neos Modules.xlf file.

```
Neos:
    modules:
      myPackage:
        label: 'Vendor.Package:Modules:my.label'
        controller: Vendor\Package\Foo\Controller\ModuleController
        description: 'Vendor.Package:Modules:my.description'
        icon: icon-graduation-cap
        submodules:
          users:
            label: 'Vendor.Package:Modules:users.label'
            controller: Vendor\Package\Platform\Controller\Module\UserController
            description: 'Vendor.Package:Modules:users.description'
            icon: icon-users
```

### Steps to Reproduce

1. Create a module with language label keys
2. Log in to backend
3. Tab on the side menu
3. And your Module has nice language label keys next to the icon

#### Expected behavior

Rendered language labels

#### Actual behavior

See at the screenshot ... the labels are manipulated and I know that I don't have such labels ;)
<img width="321" alt="bildschirmfoto 2018-04-04 um 20 05 26" src="https://user-images.githubusercontent.com/1014126/38325583-b267b96c-3843-11e8-9c06-380a1fdb14ae.png">

### Affected Versions

Neos: 3.3

UI: 1.0.9
