### ISSUE TITLE
createNew in references editor doesn't write given string to title of new node 

### ISSUE THREAD

**Issue by nicopesi** [neos/neos-ui#1764]
### Description

Created a references editor for tagging a node with the createNew option. Followed the instructions here: http://neos.readthedocs.io/en/stable/References/PropertyEditorReference.html#property-type-reference-references-referenceeditor-referenceseditor-reference-selection-editors

New Node is created correctly in the given path and with the given type.
But the given string is not passed to the created Nodes Title.

The option titleProperty: 'title' doesn't help either.

Am i missing something, or is this a bug?

### Steps to Reproduce

1. Create a node type with property type references selecting only my "FormatD.Website:TeamDepartment" - NodeType
2. Option createNew with given Path and Type "FormatD.Website:TeamDepartment"
3. New Node is created properly, but doesn't set the given string as title for the new node

Code:
```
'FormatD.Website:TeamDepartment':
  superTypes:
    'Neos.Neos:Content': TRUE
  ui:
    label: 'Team Department'
    group: 'general'
    inspector:
      groups:
        settings:
          label: 'Settings'
  properties:
    title:
      type: string
      ui:
        label: 'Title'
        inspector:
          group: 'settings'
```

```
department:
  type: references
  ui:
    label: 'Department'
    inspector:
      group: 'settings'
      editorOptions:
        nodeTypes: ['FormatD.Website:TeamDepartment']
        createNew:
          path: /sites/formatd-website/main/node-0ra4dr6pc4pod/main/node-ybf6qemgwhb5o/filter
          type: 'FormatD.Website:TeamDepartment'
          titleProperty: 'title'
```

#### Expected behavior

As described in the Docs:
"The given string is passed to the title property of the new node."

#### Actual behavior

The given string is NOT passed to the title property of the new node.
The Default Node Name is displayed instead and the title property of my new node stays empty.
Also no other property like name etc is replaced.

![bildschirmfoto 2018-04-11 um 10 06 23](https://user-images.githubusercontent.com/35302748/38605679-50a61738-3d74-11e8-8778-9af8fbd46bb1.png)
create New is working

![bildschirmfoto 2018-04-11 um 10 07 32](https://user-images.githubusercontent.com/35302748/38605695-57dddf22-3d74-11e8-8d2a-c92a6195c9a8.png)
strange that already here the string ist not passed

![bildschirmfoto 2018-04-11 um 10 06 46](https://user-images.githubusercontent.com/35302748/38605703-5b74dcf8-3d74-11e8-99e2-8a1e8e67e688.png)
Results in structure: Node Types with default Name, and no given string. The first ones were added manually. Changing title in inspector does work and is also selectable in the reference editor.

### Affected Versions

Neos:
3.3.9

UI:
1.0.9
