### ISSUE TITLE
reloadPageIfChanged does not work since Version 1.0.14

### ISSUE THREAD

**Issue by sbruggmann** [neos/neos-ui#1849]
```
'Vendor.Package:NodeType':
  properties:
    myProperty:
      ui:
        reloadPageIfChanged: true # does not work
        reloadIfChanged: true     # does work
```

Instead of reloading the page, the red error message "Unexpected token < in JSON at position 0" appears.

### Affected Versions

neos/neos-ui 1.0.14
neos/neos 3.3.9
