### ISSUE TITLE
Dimension selector does not deactivate invalid combinations

### ISSUE THREAD

**Issue by DrillSergeant** [neos/neos-ui#1851]
### Scenario

You need to habe a dimension configuration with two dimension where not all combinations are allowed. Like this:

```
Neos:
  ContentRepository:
    contentDimensions:
      country:
        label: 'Country'
        icon: icon-globe
        default: 'global'
        defaultPreset: global
        presets:
          global:
            label: 'Global'
            values:
              - global
            uriSegment: 'global'
          ch:
            label: 'Schweiz'
            values:
              - ch
              - global
            uriSegment: 'ch'
            constraints:
              language:
                'de': true
                'fr': true
                '*': false
          de:
            label: 'Deutschland'
            values:
              - de
              - global
            uriSegment: 'de'
            constraints:
              language:
                'de': true
                '*': false
      language:
        label: 'Language'
        icon: icon-language
        default: 'en'
        defaultPreset: en
        presets:
          en:
            label: 'English'
            values:
              - en
            uriSegment: 'en'
          de:
            label: 'Deutsch'
            values:
              - de
            uriSegment: 'de'
          fr:
            label: 'Français'
            values:
              - fr
            uriSegment: 'fr'
```
In this configuration "Schweiz/english" or "Deutschland/english" is not allowed.

### Steps to Reproduce
1. Try to select an invalid combination like "Schweiz/english"

#### Expected behavior
You should not be able to select them like it was in UI Version 1.0.11:
![image](https://user-images.githubusercontent.com/883552/39617889-af1d3750-4f81-11e8-9492-274c89eac751.png)

#### Actual behavior
You can select every combination and if you select an invald one you end in an 404 error because the combination does not exist.
![image](https://user-images.githubusercontent.com/883552/39617934-d5626ed0-4f81-11e8-9675-780d5274c1e6.png)

### Affected Versions

Neos: 3.3.9
UI: 1.0.13/14

It worked as expeced in UI 1.0.11.  Don't know if the bug was introduced in 1.0.12 or 1.0.13.
