### ISSUE TITLE
Feature: Make canvas background color configurable for editorPreviewModes

### ISSUE THREAD

**Issue by akappler** [neos/neos-ui#1861]
### Description
As an integrator I'd like to define the background color of the canvas outside the content area (see picture). As most pages have a white background, this looks currently a bitt odd. As the background color depends on the project, it would be nice to set property in the `editPreviewModes` to define a background color. 

E.g.:
``` 
      editPreviewModes:
        tablet:
          isEditingMode: false
          isPreviewMode: true
          fusionRenderingPath: ''
          title: 'Diu.Templates:Main:editPreviewModes.tablet'
          position: 200
          width: 1024px
          backgroundColor: '#000000'
```
