### ISSUE TITLE
Content Dimensions contraints are not supported

### ISSUE THREAD

**Issue by dfeyer** [neos/neos-ui#1867]
Given the follwing configurations:

```yaml
Neos:
  ContentRepository:
    contentDimensions:
      country:
        default: 'fr'
        defaultPreset: 'fr'
        label: 'Country'
        icon: 'icon-globe'
        presets:
          fr:
            label: 'France'
            values: ['fr']
            uriSegment: 'fr'
            constraints:
              language:
                de_DE: false
          ch:
            label: 'Suisse'
            values: ['fr', 'ch']
            uriSegment: 'ch'
          ca:
            label: 'Canada'
            values: ['fr', 'ca']
            uriSegment: 'ca'
            constraints:
              language:
                de_DE: false

      language:
        default: 'fr_FR'
        defaultPreset: 'fr_FR'
        label: 'Language'
        icon: 'icon-language'
        presets:
          fr_FR:
            label: 'Français'
            values: ['fr_FR']
            uriSegment: 'fr'
          de_DE:
            label: 'Deutsch'
            values: ['de_DE']
            uriSegment: 'de'
```

When France or Canada are select I MUST not be able to select de_DE language dimensions

Documentation reference: https://neos.readthedocs.io/en/stable/CreatingASite/ContentDimensions.html#preset-constraints

Additionnal question here, did we enforce this only in the UI or directly in the CR ?
