### ISSUE TITLE
Non-block inline properties with RTE have leading spaces

### ISSUE THREAD

**Issue by DrillSergeant** [neos/neos-ui#1932]
### Steps to Reproduce

1. Create a content nodetype with a text-property that is inline editable and RTE enabled
```
'Internezzo.Neos:SpecialHeadline':
  superTypes:
    'Neos.Neos:Content': true
  ui:
    label: 'Special Headline'
    group: 'general'
  properties:
    headline:
      type: 'string'
      defaultValue: ''
      ui:
        inlineEditable: true
        aloha:
          placeholder: 'put in your text here'
```
2. Define the rendering in Fusion
```
prototype(Internezzo.Neos:SpecialHeadline) < prototype(Neos.Fusion:Tag) {
    tagName = 'span'
    content = ${q(node).property('headline')}
    @process.contentElementEditableWrapping = Neos.Neos:ContentElementEditable {
        property = 'headline'
    }
    @process.contentElementWrapping = Neos.Neos:ContentElementWrapping {
        @position = 'end'
    }
}
```
3. Go to the backend
4. Add a content node of the new type
5. Insert some text into it via inline editing
6. Publish the changes
7. Inspect the rendered content in the frontend

#### Expected behavior
I see a span-tag with my content inside it.

#### Actual behavior
I see a span-tag with my content inside it, but the content has a leading space character. This space character is also present in the database.

#### Extra information
- When you change the tagName in the Fusion rendering to a block-element (like div), the bug does **not** happen.
- I know that I can use EEL (String.trim) to get rid of the space in the frontend, but the spaces still remain in the database

### Affected Versions
Neos: 3.3.12
UI: 1.1.1
