### ISSUE TITLE
Inline editable document properties are not getting saved completely

### ISSUE THREAD

**Issue by DrillSergeant** [neos/neos-ui#1933]
### Steps to Reproduce

1. Use the demo-package and add a new property to the page nodetype
```
'Neos.NodeTypes:Page':
  properties:
    headline:
      type: string
      defaultValue: ''
      ui:
        inlineEditable: TRUE
        aloha:
          'format': []
          'table': []
          'link': []
          'list': []
          'alignment': []
          'formatlesspaste':
            'button': FALSE
            'formatlessPasteOption': TRUE
          'autoparagraph': FALSE
          placeholder: i18n
```
2. Render the property
```
prototype(Neos.Neos:Page) {
    body.content.main {
        @process.addHeadline = Neos.Fusion:Array {
            headline = Neos.Fusion:Tag {
                tagName = 'h1'
                content = ${q(node).property('headline')}
                @process.contentElementEditableWrapping = Neos.Neos:ContentElementEditable {
                    property = 'headline'
                }
                @process.contentElementWrapping = Neos.Neos:ContentElementWrapping {
                    @position = 'end'
                }
            }
            content = ${value}
        }
    }
}
```
3. Now go to the backend, add a new page document and enter some code into the inline property
4. Save and publish it
5. Open in in the frontend

#### Expected behavior

I see my entered content.

#### Actual behavior

I see just a part of my entered content. 

See this video:
![screencast](https://user-images.githubusercontent.com/883552/42017884-c099914a-7ab0-11e8-9207-9a656fc1b1bd.gif)

If you reload the backend document you see that indeed part of the entered content is not saved. Worst part of it is that the editor might not recognize that something got lost after publishing if he does not control the frontend.

### Affected Versions

Neos: 3.3.12
UI: 1.1.1
