### ISSUE TITLE
CodeEditor not working in Firefox

### ISSUE THREAD

**Issue by DrillSergeant** [neos/neos-ui#2001]
Property-Editor **CodeEditor** not working in Firefox.

### Steps to Reproduce

1. Create a nodetype with a property that used the CodeEditor
```
'Internezzo.Neos:EditorTest':
  superTypes:
    'Neos.Neos:Content': true
  ui:
    label: 'Code Editor'
    group: 'general'
    inspector:
      groups:
        test:
          label: 'Code-Editor'
          icon: 'icon-envelope-o'
  properties:
    test:
      type: 'string'
      defaultValue: ''
      ui:
        inspector:
          group: test
          editor: 'Neos.Neos/Inspector/Editors/CodeEditor'
          editorOptions:
            buttonLabel: i18n
```
2. Add a node of this type
3. Try to edit the property with the codeEditor

#### Expected behavior
You can edit the code in the CodeEditor

#### Actual behavior
In Chrome it works fine.
In Firefox (here Windows, 60.0.2 (64-Bit)) this happens:
![image](https://user-images.githubusercontent.com/883552/42631562-cc3f4be0-85da-11e8-805f-6722600f2d77.png)

### Affected Versions
Neos: 3.3.9
UI: 1.1.2 (and also in 1.2.3)
