### ISSUE TITLE
META: CKE5 integration

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#2002]
### How to test?

The default text editor is now configurable in Settings.yaml:

```
Neos:
  Neos:
    Ui:
      frontendConfiguration:
        defaultInlineEditor: 'ckeditor5'
```

### TODO:

- [x] wait for  removeformat to be implemented in https://github.com/ckeditor/ckeditor5/issues/908
- [x] test, make sure it's rock solid, then release a major version making CKE5 the default editor
- [ ] ctrl+k should open link editor
