### ISSUE TITLE
Keyboard shortcut Feature deactivation

### ISSUE THREAD

**Issue by KPeschke** [neos/neos-ui#2014]
### Description
I have tried to disable the hotkeys, but the button in backend is still visible.

### Steps to Reproduce
```
Neos:
  Neos:
    Ui:
      frontendConfiguration:
        hotkeys: null
```

Also tried with `false` and `[]` alwas the same result.

#### Actual behavior
The button is still visible in backend.

![image](https://user-images.githubusercontent.com/8969952/42636196-6ed08718-85e8-11e8-8fc5-9fb06ad9f88d.png)

### Affected Versions
Neos: 3.3.12
UI: 1.1.2
