### ISSUE TITLE
Collapsed NodeType group isn't collapsed

### ISSUE THREAD

**Issue by mstruebing** [neos/neos-ui#2020]
```
Neos:
  Neos:
    nodeTypes:
      groups:
        plugins:
          position: 200
          label: 'Neos.Neos:Main:nodeTypes.groups.plugins'
          collapsed: true
```

This doesn't render the group as collapsed.
