### ISSUE TITLE
Image cropping restrictions are aplied on crop-editing only not on asset-selecting

### ISSUE THREAD

**Issue by mficzel** [neos/neos-ui#2024]
If images-properties have cropping restriction those are only active in the crop dialog but are not applied once images are selected. That way images with the wrong aspect ratio end up in the cr.

```
    image:
      type: Neos\Media\Domain\Model\ImageInterface
      ui:
        label: 'Image'
        reloadIfChanged: true
        inspector:
          editorOptions:
            features:
              crop: true
              resize: false
            crop:
              aspectRatio:
                locked:
                  width: 320
                  height: 552
```
#### Expected behavior

If cropping restrictions are active a default crop for the expected aspect ratio should be created if the current aspect ratio does not match the requirement.

#### Actual behavior

The Image is selected without crop, only if the crop-dialog is opened the aspect ratio gets enforced.

### Affected Versions

Tested on Neos 3.3 with UI 1.2, i am quite sure this feature simply was not implemented yet.
