### ISSUE TITLE
Selectbox Type Array not working anymore (since 1.3)

### ISSUE THREAD

**Issue by h1Modeling** [neos/neos-ui#2042]
### Description

Values are displayed but they are not selectable anymore

### Steps to Reproduce

1. Create property of type array
 
```yaml
   test:
      type: array
      ui:
        label: 'test'
        inspector:
          group: 'general'
          editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
          editorOptions:
            values:
              test1:
                label: 'test1'
              test2:
                label: 'test2'
              test3:
                label: 'test3'
              test4:
                label: 'test4'
```

2. Try to select an element
3. Neos just shows the placeholder value

<img width="320" alt="bildschirmfoto 2018-07-28 um 16 14 09" src="https://user-images.githubusercontent.com/17990673/43357411-4d83a770-9281-11e8-8c5e-ebce9ade4f9f.png">

### Affected Versions

Neos: 4.0

UI: 1.3.0
