### ISSUE TITLE
LinkEditor restrict assets

### ISSUE THREAD

**Issue by simplesolution** [neos/neos-ui#2063]
### Description

When setting editorOptions of the LinkEditor to `assets: false` assets still can be selected.
### Steps to Reproduce

1.
```
link:
  type: string
  ui:
    label: i18n
    reloadIfChanged: true
    inspector:
      group: link
      editor: 'Neos.Neos/Inspector/Editors/LinkEditor'
      editorOptions:
        assets: false
```
2. Search for an asset in the inspector
3. Notice that assets still can be selected

#### Expected behavior

Assets should not appear in the LinkEditor searchbox and the user should not be able to select an assset.

#### Actual behavior

Assets can be selected in the inspector.

### Affected Versions

Neos: 4.0.0

UI: 1.3.2
