### ISSUE TITLE
Deactivating node tree preset leaves stale nodes in tree

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-ui#2069]
### Description

With configured presets (as per https://github.com/neos/neos-ui/pull/2048) limiting the shown nodes to a preset works fine. But when resetting the preset, the nodes that were shown for that preset are simply kept at the end of the "new tree content" that is loaded with the reset.

Only when reloading the tree afterwards, those nodes disappear.

### Steps to Reproduce

Limit to a preset:

<img width="158" alt="limited-to-preset" src="https://user-images.githubusercontent.com/95873/44075187-0730fbce-9f9c-11e8-9211-66af7ac597f9.png">

Click the preset reset icon:

<img width="160" alt="preset-reset" src="https://user-images.githubusercontent.com/95873/44075243-53da876a-9f9c-11e8-9c48-a06cd306328a.png">

The nodes formerly shown are still there. Reloading the tree once makes the disappear.

### Affected Versions

Neos: 4.0.7

**Comment by bwaidelich** [comment]
meh, too bad.. I can't look into this one right now, but I'll check asap if noone else does before!

**Comment by bwaidelich** [comment]
It seems like this bug already existed before:
When hiding certain document types per default via
```
Neos:
  Neos:
    userInterface:
      navigateComponent:
        nodeTree:
          presets:
            default:
              baseNodeType: 'Neos.Neos:Document,!Neos.Demo:Chapter'
```
They still appear in the tree when changing the filter  forth and back:
![image](https://user-images.githubusercontent.com/307571/44258849-3cead700-a210-11e8-8a15-770ca59aafe1.png)

![image](https://user-images.githubusercontent.com/307571/44258862-45dba880-a210-11e8-9737-5e6807344969.png)

![image](https://user-images.githubusercontent.com/307571/44258887-51c76a80-a210-11e8-8abe-d90872bd25fe.png)

Probably a regression of the React UI!?
