### ISSUE TITLE
SelectBoxEditor values are not sorted correctly

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-ui#2071]
If I create a `SelectBoxEditor` and set some values, the order is not the same as it is defined in the `yaml` file:

```yaml
  properties:
    icon:
      type: string
      defaultValue: mountains
      ui:
        label: Icon
        reloadIfChanged: true
        inspector:
          group: image
          editor: Neos.Neos/Inspector/Editors/SelectBoxEditor
          position: 10
          editorOptions:
            allowEmpty: true
            values:
              door-sign:
                label: 'Door sign'
              double-bed:
                label: 'Double bed'
              golfball:
                label: 'Golf ball'
              golfflag:
                label: 'Golf flag'
              key:
                label: Key
              moon:
                label: 'Moon with stars'
              mountains:
                label: Mountains
              skis-with-poles:
                label: 'Skis with poles'
              skis-poles:
                label: 'Skis poles'
              skis:
                label: Skis
              snow:
                label: Snowflake
              sun-bath:
                label: 'Sun bath'
              swimming-pool:
                label: 'Swimming pool'
              water:
                label: 'Water'
```

Result:

<img width="309" alt="screenshot 2018-08-14 12 09 25" src="https://user-images.githubusercontent.com/4510166/44085837-f98943f4-9fba-11e8-87d8-e27c43dd291b.png">
