### ISSUE TITLE
Input for property with IntegerValidator is accepted, even if it only starts with an integer

### ISSUE THREAD

**Issue by dennisirmscher** [neos/neos-ui#2080]
### Description

When creating a node type with a property using the integer-validator any value starting with an integer is accepted as valid:

![image](https://user-images.githubusercontent.com/16836984/44348748-a29ec380-a49b-11e8-9ca6-b636d5e1c648.png)

### Steps to Reproduce

1. Create a node type with a property using the integer-validator, e.g.:

```
minValue:
  type: string
  defaultValue: null
  ui:
    label: someLabel
    inspector:
      group: someGroup
  validation:
    'Neos.Neos/Validation/IntegerValidator': []
```

2. Enter a value starting with an integer followed by any other character

#### Expected behavior

The value is marked as invalid.

#### Actual behavior

The value is accepted as valid.

### Affected Versions

Neos: 3.3.13 LTS
UI: 1.3.2
