### ISSUE TITLE
Refresh NodeTree does not work when the NodeType filter is used

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-ui#2093]
### Description

When the NodeType filter is active, hitting the "Refresh" button results in a broken Node Tree & Inspector

### Steps to Reproduce

1. Use the `NodeType` filter to filter the tree for a node type or preset
2. Hit the "Refresh" button above the tree

#### Expected behavior

Node tree should be reloaded, inspector reflect the currently selected node

#### Actual behavior

The Node Tree shows an invalid result and the inspector keeps loading:

![image](https://user-images.githubusercontent.com/307571/44513029-93e32700-a6bc-11e8-891f-7946184cdc93.png)

The latter even happens if the filter is reset before hitting the "Refresh" button!

### Affected Versions

Neos: dev-master

UI: dev-master  de87d33

**Comment by sbruggmann** [comment]
For me not reproducable anymore.
@bwaidelich Needs this issue still work?

**Comment by bwaidelich** [comment]
Thanks for the pointer – I assume this one was resolved with #2076

**Comment by bwaidelich** [comment]
I have to reopen this one as the issue still persists for me unfortunately.
Not by filtering for node types, but for custom *presets*.

## Steps to reproduce

Add some preset via `Settings.yaml`:

```yaml
Neos:
  Neos:
    userInterface:
      navigateComponent:
        nodeTree:
          presets:
            'default':
              baseNodeType: 'Neos.Neos:Document,!Neos.Demo:Chapter'
            'legalPages':
              ui:
                label: 'Test Preset'
              baseNodeType: 'Neos.Demo:Chapter'
```

...follow the "steps to reproduce" from above
