### ISSUE TITLE
Dimensions not selectable from the dimensions menu

### ISSUE THREAD

**Issue by dennisirmscher** [neos/neos-ui#2101]
### Description

If you configure two dimensions-sets with one combination which is completely separated from all others, it is impossible to select this specific one from the dimensions menu in the backend. It is grayed out due to the constraints set.

Here is an example configuration:

```
Neos:
  ContentRepository:
    contentDimensions:
      'country':
        default: 'deu'
        defaultPreset: 'deu'
        label: 'Country'
        icon: 'icon-globe'
        presets:
          'deu':
            label: 'Germany'
            values: ['deu']
            uriSegment: 'deu'
          'aut':
            label: 'Austria'
            values: ['aut', 'deu']
            uriSegment: 'aut'
          'lux':
            label: 'Luxembourg'
            values: ['lux', 'deu']
            uriSegment: 'lux'
          'dnk':
            label: 'Denmark'
            values: ['dnk']
            uriSegment: 'dnk'
      'language':
        default: 'de'
        defaultPreset: 'de'
        label: 'Language'
        icon: 'icon-language'
        presets:
          'de':
            label: 'German'
            values: ['de']
            uriSegment: 'de'
            constraints:
              country:
                '*': false
                'deu': true
                'aut': true
                'lux': true
          'en':
            label: 'English'
            values: ['en']
            uriSegment: 'en'
            constraints:
              country:
                '*': false
                'deu': true
                'aut': true
          'da':
            label: 'Danish'
            values: ['da']
            uriSegment: 'da'
            constraints:
              country:
                '*': false
                'dnk': true
```

With this, you can't choose "Denmark" or "Danish" from the dimensions menu, as Denmark ist prohibited in the languages English and German while Danish is prohibited in Germany, Austria and Luxembourg:

![image](https://user-images.githubusercontent.com/16836984/44585014-23670380-a7ab-11e8-95f9-83ca80466f06.png)
![image](https://user-images.githubusercontent.com/16836984/44585040-3548a680-a7ab-11e8-8e34-ff1c0951860e.png)

On the other hand, if you enter the danish dimension via the URI, you can't switch back to any other dimension from the menu:

![image](https://user-images.githubusercontent.com/16836984/44584961-f155a180-a7aa-11e8-99f8-58d352ee350d.png)
![image](https://user-images.githubusercontent.com/16836984/44584980-00d4ea80-a7ab-11e8-957a-47a247ef9043.png)

#### Expected behavior

Any ability to choose the Danish dimension from the menu.

#### Actual behavior

Not to have that ability...

### Affected Versions

Neos: 3.3.13

UI: 1.3.3
