### ISSUE TITLE
Neos 4.1: cant format any text via CK

### ISSUE THREAD

**Issue by breadlesscode** [neos/neos-ui#2113]
### Description
I have no formatting options, since the Neos upgrade.

### Steps to Reproduce

1. Update neos/neos & neos/neos-ui

#### Expected behavior
Can format text

#### Actual behavior
No formatting options shown (underline e.g.).
![No formatting options](https://user-images.githubusercontent.com/5465112/44909708-ac88b800-ad20-11e8-92c8-591dd20318ac.png)

### Affected Versions
Neos: 4.1
UI: 1.3.3

### Node Configuration 

```yaml
'Vendor.Xy:Content.Text':
  superTypes:
    'Neos.Neos:Content': true
    'Vendor.Xy:Mixin.Anchorable': true
  ui:
    label: 'Text'
    icon: 'align-center'
    group: 'general'
    inspector:
      groups:
        text:
          label: 'Text'
  properties:
    text:
      type: string
      ui:
        label: 'Text'
        inlineEditable: true
        inline:
          editorOptions:
            autoparagraph: true
            'format':
              'strong': true
              'em': true
              'u': true
              'sub': true
              'sup': true
              'del': true
              'p': true
              'h1': true
              'h2': true
              'h3': true
              'pre': true
              'removeFormat': true
            'alignment':
              'left': true
              'center': true
              'right': true
              'justify': true
            'table':
              'table': true
            'list':
              'ol': true
              'ul': true
            'link':
              'a': true
            formatlesspaste:
              'button': true

```

**Comment by breadlesscode** [comment]
```yaml 
  properties:
    text:
      type: string
      ui:
        label: 'Text'
        inlineEditable: true
        inline:
          editorOptions:
            placeholder: i18n
            autoparagraph: true
            linking:
              anchor: true
              title: true
              relNofollow: true
              targetBlank: true
            formatting:
              strong: true
              em: true
              u: true
              sub: true
              sup: true
              del: true
              p: true
              h1: true
              h2: true
              h3: true
              h4: true
              h5: true
              h6: true
              pre: true
              underline: true
              strikethrough: true
              removeFormat: true
              left: true
              right: true
              center: true
              justify: true
              table: true
              ol: true
              ul: true
              a: true
```

The new syntax isnt working also
