### ISSUE TITLE
Linkeditor options missing

### ISSUE THREAD

**Issue by KPeschke** [neos/neos-ui#2214]
### Description
Since version 1.3.4 we miss the new ckeditor5 link editor options.

### Steps to Reproduce
1. use this yaml snippit
```
  properties:
    text:
      type: string
      defaultValue: ''
      ui:
        inlineEditable: true
        inline:
          editorOptions:
            placeholder: i18n
            autoparagraph: true
            linking:
              anchor: true
              title: true
              relNofollow: true
              targetBlank: true
            formatting:
              strong: true
              removeFormat: true
              ul: true
              a: true
```
2. set a link

#### Expected behavior
Neos v3.3.14 & UI v1.3.3
![image](https://user-images.githubusercontent.com/8969952/48011298-abf50f00-e11f-11e8-8795-4527b2dc1dc0.png)

#### Actual behavior
Neos v3.3.15 & UI v1.3.4
![image](https://user-images.githubusercontent.com/8969952/48011366-d1821880-e11f-11e8-8b5e-d276bcad4114.png)

### Affected Versions
Neos: v3.3.15
UI: v1.3.4
