### ISSUE TITLE
"0" integer option not selected in SelectBoxEditor

### ISSUE THREAD

**Issue by futape** [neos/neos-ui#2252]
### Description

say i have a nodetype with an integer inspector property using the SelectBoxEditor:

```
widthMd:
  type: integer
  defaultValue: 0
  ui:
    label: i18n
    reloadIfChanged: true
    inspector:
      group: 'column'
      position: 30
      editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
      editorOptions:
        values:
          -1:
            label: 'Avency.Neos.BaseNodeTypes:NodeTypes.Content.Column:width.none'
          0:
            label: 'Avency.Neos.BaseNodeTypes:NodeTypes.Content.Column:width.0'
          12:
            label: 'Avency.Neos.BaseNodeTypes:NodeTypes.Content.Column:width.12'
```

when i select "12" in inspector, the value is saved properly to the nodedata and after refreshing the page, "12" is selected in the editor.
the same goes for "-1".
however, when i select "0", the value is saved to the nodedata, but after refreshing the page, no option is selected in the editor and it requests me to choose one. seems as if an integer value of 0 is considered empty.

as a workaround i changed the property to a string one and it works just fine. however, i think this should be fixed.

#### Expected behavior

The option with the "0" value should be selected after refreshing the page.

#### Actual behavior

The SelectBoxEditor requests me to select an option since none is chosen.

### Affected Versions

Neos: 4.0.10

UI: 1.4.1
