### ISSUE TITLE
SelectBoxEditor with DataSource and option multiple does not display active selection

### ISSUE THREAD

**Issue by nlx-lars** [neos/neos-ui#2253]
### Description

When using a Datasource for a SelectBox Editor in the Inspector with "multiple: true", the active values are not displayed in the Editor, even though they get saved correctly.

### Steps to Reproduce

1. Create DataSource
```
use Neos\ContentRepository\Domain\Model\NodeInterface;
use Neos\Flow\Annotations as Flow;
use Neos\Flow\Persistence\PersistenceManagerInterface;
use Neos\Neos\Domain\Model\Site;
use Neos\Neos\Domain\Repository\SiteRepository;
use Neos\Neos\Service\DataSource\AbstractDataSource;
use Neos\Utility\TypeHandling;

class SitesDataSource extends AbstractDataSource
{

    /**
     * @var string
     */
    protected static $identifier = 'test-test-sites';

    /**
     * @Flow\Inject
     * @var PersistenceManagerInterface
     */
    protected $persistenceManager;

    /**
     * @Flow\Inject
     * @var SiteRepository
     */
    protected $siteRepository;

    /**
     * @param NodeInterface|null $node
     * @param array $arguments
     * @return array
     */
    public function getData(NodeInterface $node = null, array $arguments)
    {
        return array_map(function(Site $site) {
            return [
                'value' => [
                    '__identity' => $this->persistenceManager->getIdentifierByObject($site),
                    '__type' => TypeHandling::getTypeForValue($site)
                ],
                'label' => $site->getName(),
                'icon' => 'globe'
            ];
        }, $this->siteRepository->findAll()->toArray());
    }

}
```
2. Create NodeType with SelectBoxEditor, DataSource and multiple
```
'Test.Test:Test':
  superTypes:
    'Neos.Neos:Content': true

  ui:
    label: 'Test Node Type'
    group: 'general'
    icon: 'chevron-right'
    inspector:
      groups:
        selects:
          label: 'Selects'
          icon: 'chevron-right'
          position: 10


  properties:

    singleSelect:
      type: 'Neos\Neos\Domain\Model\Site'
      ui:
        label: 'Single Select'
        inspector:
          group: selects
          editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
          editorOptions:
            dataSourceIdentifier: 'test-test-sites'

    multiSelect:
      type: 'array<Neos\Neos\Domain\Model\Site>'
      ui:
        label: 'Multi Select'
        inspector:
          group: selects
          editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
          editorOptions:
            dataSourceIdentifier: 'test-test-sites'
            multiple: true
```
3. Create Node in Backend and try to select a Site in the Inspector

#### Expected behavior

The selected value for the "multiSelect" property should be displayed correctly, just like for the property "singleSelect"

#### Actual behavior

The active values are not marked as active in the inspector for the multiselect. 

![bildschirmfoto 2018-11-20 um 17 11 58](https://user-images.githubusercontent.com/15905038/48786778-d29e7280-ece7-11e8-9472-e2b1cc8edb2f.png)
![bildschirmfoto 2018-11-20 um 17 11 53](https://user-images.githubusercontent.com/15905038/48786776-d29e7280-ece7-11e8-94a1-38046865bd04.png)

### Affected Versions

Neos: 4.1.8

UI: 1.4.1
