### ISSUE TITLE
Editing in preview mode

### ISSUE THREAD

**Issue by pmaas** [neos/neos-ui#2316]
### Description

It seems that there is no difference between editing and preview mode anymore. 

### Steps to Reproduce

Change from in place editing mode to (custom) preview mode.

#### Expected behavior

Inside preview mode it should't be possible to edit content.

#### Actual behavior

<img width="699" alt="bildschirmfoto 2019-01-30 um 21 07 59" src="https://user-images.githubusercontent.com/2778669/52009594-9b142980-24d3-11e9-8a50-0e48c8bd722a.png">

```
Neos:
  Neos:
    userInterface:
      editPreviewModes:
        tablet:
          title: 'Tablet'
          isEditingMode: false
          isPreviewMode: true
          position: 200
          width: 768
          height: 1024
          backgroundColor: '#3f3f3f'
        mobile:
          ...
```

### Affected Versions

Neos: 4.2.4
UI: 3.0.0
