### ISSUE TITLE
Asset editor doesn't respect 'editorOptions: accept' values

### ISSUE THREAD

**Issue by pmaas** [neos/neos-ui#2320]
### Description

If you use the media browser to select an asset, the ui don't respect the selected mime type.

### Steps to Reproduce

Select an asset with wrong mime type and apply changes.

#### Expected behavior

Show only assets with selected mime type inside the media browser.

#### Actual behavior

![screeny video 31 01 2019 12 07 48 1](https://user-images.githubusercontent.com/2778669/52050708-ae65da00-2551-11e9-9155-0ebf5b4f977b.gif)

```
  properties:
    mp4:
      type: 'Neos\Media\Domain\Model\Asset'
      ui:
        label: i18n
        reloadIfChanged: true
        inspector:
          editorOptions:
            accept: 'video/mp4'
```

### Affected Versions

Neos: 4.2.4
UI: 3.0.1

**Comment by dimaip** [comment]
Just curious, did it work in 1.x?

**Comment by pmaas** [comment]
> Just curious, did it work in 1.x?

Havn't tried it with 1.x. I can test it later.

**Comment by dimaip** [comment]
Ok, nevertheless bugfix wanted :)

**Comment by pmaas** [comment]
Ok, looked a bit deeper into this issue: 

Currently the url for the [MediaSelectionScreen](https://github.com/neos/neos-ui/blob/be315ca5811c6cf9e32626a04a564cc108399d48/packages/neos-ui-editors/src/SecondaryEditors/MediaSelectionScreen/index.js) is build like this: `${mediaBrowserUri}/${type}.html`. As `type` there are two allowed values `assets` and `images`. Additionally inside the media browser there is a `filter` argument which can be filled with the following values `All`, `Image`, `Document`, `Video` and `Audio` ([see](https://github.com/neos/neos-development-collection/blob/edcfb3dd4c0983b683f1ed287480192d02f5621a/Neos.Media/Classes/Domain/Model/AssetSource/Neos/NeosAssetProxyRepository.php#L73)). A possibility to filter the media browser by an given mime type is not present at the moment.

Maybe it could be a first step to define the `filter` inside the `editorOptions`. The better but more complex solution would be to extend the media browser to be able to filter for specific mime types.

Any thoughts / hints to this? :)

**Comment by jonnitto** [comment]
Any progress on this?

**Comment by pmaas** [comment]
No unfortunately not :( [Asked on slack for hints](https://neos-project.slack.com/archives/C050RKUV7/p1554368631001600), but got no feedback.

**Comment by markusguenther** [comment]
This will be solved in the upcoming neos version (5.3) by the new feature:

```
'Some.Node:Type':
  properties:
    'asset':
      type: 'Neos\Media\Domain\Model\Asset'
      ui:
        inspector:
          group: 'asset'
          editorOptions:
            constraints:
              mediaTypes: ['audio/*']
              assetSources: ['neos', 'wikipedia_de']
```
