### ISSUE TITLE
Node CreationDialog media browser does not work

### ISSUE THREAD

**Issue by rolandschuetz** [neos/neos-ui#2356]
### Description

The node creationDialog shows an AssetEditor with a media browser icon, which does not work.

```yaml
    creationDialog:
      elements:
        assets:
          type: 'array<Neos\Media\Domain\Model\Asset>'
          ui:
            editor: 'Neos.Neos/Inspector/Editors/AssetEditor'
            label: 'Assets'
```

### Steps to Reproduce

1. Click on the media browser, see code above

#### Expected behavior

A media browser opens and allows a selection.

#### Actual behavior

A JavaScript error happens:
```
index.js:137 Uncaught TypeError: n.props.renderSecondaryInspector is not a function
    at AssetEditor.n.handleChooseFromMedia (index.js:137)
    at Object.da (react-dom.production.min.js:14)
    at ka (react-dom.production.min.js:15)
    at la (react-dom.production.min.js:15)
    at xa (react-dom.production.min.js:17)
    at Ba (react-dom.production.min.js:18)
    at Da (react-dom.production.min.js:18)
    at za (react-dom.production.min.js:18)
    at Ga (react-dom.production.min.js:21)
    at Fd (react-dom.production.min.js:84)
```

[Demo Video](http://youtu.be/z4MzvfIMsHI)

### Affected Versions

Neos: 4.2

UI: 3.1
