### ISSUE TITLE
Validators fails and input field is uneditable

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-ui#2452]
If you have a [validator](https://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartV/ValidatorReference.html) on a property, the backend throws an error: 
```
Argument 3 passed to Neos\Neos\Ui\Service\NodePropertyValidationService_Original::validate() must be of the type array, boolean given
```

### Steps to Reproduce

Create a property with a validator: 
```yaml
  properties:
    title:
      type: string
      validation:
        'Neos.Neos/Validation/LabelValidator': true
```

Try to edit the value => You will get the error

<img width="492" alt="Bildschirmfoto 2019-04-10 um 15 05 49" src="https://user-images.githubusercontent.com/4510166/55881032-2da30a00-5ba2-11e9-9ad4-c9c23bd4977d.png">

### Affected Versions

Neos: 4.3-dev // 4.2

UI: dev-master // 3.2

**Comment by jonnitto** [comment]
If you set the validator like this: 
```yaml
properties:
    title:
      type: string
      validation:
        'Neos.Neos/Validation/LabelValidator': []
```
everything works. Still, it is a breaky behavior, because before also boolean values worked
