### ISSUE TITLE
CKEditor SelectBox empty when no headline is allowed

### ISSUE THREAD

**Issue by darmstaedter** [neos/neos-ui#2480]
### Description

When you use CKEditor on a property and disallow all headlines, the select box is empty. As soon as you allow one headline type – it's all fine.

(I realized this issue because in Safari an empty select box isn't in the right place. A comment is under the [specific issue](https://github.com/neos/neos-ui/issues/1473#issuecomment-491930165).)

### Steps to Reproduce

1. Add a document type with the following property:
```yaml
  properties:
    description:
      type: string
      defaultValue: 'Was muss getan werden…'
      ui:
        inlineEditable: true
        aloha:
          placeholder: i18n
          autoparagraph: true
          'format':
            'strong': true
            'em': true
            'u': false
            'sub': false
            'sup': false
            'del': false
            'p': true
            'h1': false
            'h2': false
            'h3': false
            'pre': true
            'removeFormat': true
          'table':
            'table': false
          'list':
            'ol': true
            'ul': true
          'link':
            'a': true
```
2. Make this property inline editable:
```
main = Neos.Neos:ContentComponent {
  description = Neos.Neos:Editable {
    property = 'description'
    block = true
  }
  renderer = afx`
    <div>{props.description}</div>
  `
}
```

3. In Neos click on the property in the main editing window and add some content.

#### Expected behavior
The select box should show Paragraph.

<img width="395" alt="image" src="https://user-images.githubusercontent.com/873002/57644008-6ed07480-75bb-11e9-8140-5e88e93d1b50.png">

#### Actual behavior
The select box is empty.

<img width="407" alt="image" src="https://user-images.githubusercontent.com/873002/57642423-91f92500-75b7-11e9-983b-a6cb0a74597f.png">

It's not empty as soon as you add one headline type. It doesn't matter which one.

<img width="464" alt="image" src="https://user-images.githubusercontent.com/873002/57643070-244df880-75b9-11e9-91c1-7635819c6693.png">

### Affected Versions

Browser: Safari 12.1

Neos: 4.3.0

UI: 3.3.0
