### ISSUE TITLE
Labels and icons in ContentCollections

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-ui#2503]
At the moment, it is not possible to define own icon and/or label for `Neos.Neos:ContentCollection`.

**Comment by markusguenther** [comment]
Ok after a call with Jon it is now clearer what he wants to achieve.

The Problem is that you can always define icons and labels for nodes or new node types, but not for the ```Neos.Neos:ContentCollection``` itself.

<img width="317" alt="Other_elements_-_Features_-_Neos_Demo_Site_-_Vivaldi" src="https://user-images.githubusercontent.com/1014126/58255365-1f353a00-7d6d-11e9-9ee0-c517486c50a5.png">

So it is more or less a feature to resolve this inconsistency.
It would be better to have own labels sometimes and configure own icons than the folder.

**Comment by markusguenther** [comment]
Before I dive deeper into the rendering of the content tree.
Is it ok to adjust the icon and label like that for the content collections? Or any other suggestions?

```
'Neos.NodeTypes:Page':
  childNodes:
    'main':
      ui:
        icon: 'icon-star'
        label: 'Main'
    'teaser':
      type: 'Neos.Neos:ContentCollection'
      ui:
        icon: 'icon-star'
        label: 'Teaser'
      constraints:
        nodeTypes:
          '*': FALSE
          'Neos.NodeTypes:Headline': TRUE
          'Neos.NodeTypes:Text': TRUE
          'Neos.NodeTypes:Image': TRUE
```

I am still searching the piece of code where the node label is generated because it does not happen in the node component of the tree itself. But will try to investigate that.
