### ISSUE TITLE
Linking options are missing

### ISSUE THREAD

**Issue by KPeschke** [neos/neos-ui#2535]
### Description

Since version v2.8.0 we miss the linking options.

### Steps to Reproduce

1. use this yaml snippit
```
  properties:
    text:
      type: string
      defaultValue: ''
      ui:
        inlineEditable: true
        inline:
          editorOptions:
            placeholder: i18n
            autoparagraph: true
            linking:
              anchor: true
              title: true
              relNofollow: true
              targetBlank: true
            formatting:
              strong: true
              removeFormat: true
              ul: true
              a: true
```
2 . set a link

#### Expected behavior

![image](https://user-images.githubusercontent.com/8969952/61808367-863da080-ae3b-11e9-98e3-1d0e49780cf0.png)

#### Actual behavior

![image](https://user-images.githubusercontent.com/8969952/61808444-b127f480-ae3b-11e9-9ea3-2f9b38946b6c.png)

### Affected Versions

Neos: v3.3.23
UI: v2.8.0
