### ISSUE TITLE
navigateComponent loadingDepth doesn't work

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-ui#2536]
### Description

The setting `Neos.Neos.navigateComponent.nodeTree.loadingDepth` doesn't work anymore

### Steps to Reproduce

Add this to your `Settings.yaml`

```yaml
Neos:
  Neos:
    navigateComponent:
      nodeTree:
        loadingDepth: 1
      structureTree:
        loadingDepth: 2
```

#### Expected behavior

- Only the first level in the node tree is shown
- Only the first two levels in the structure tree are shown

#### Actual behavior

All levels are show

### Affected Versions

Neos: 4.3.3

UI: 3.7.0 & 3.8.0
