### ISSUE TITLE
Dimension change not possible, when uriSegment is not set.

### ISSUE THREAD

**Issue by Stefan-Kosker** [neos/neos-ui#2542]
Currently, when dimensions are created and no uriSegment is set, you can't change the backend dimension.

Example Dimension Config: 
```
Neos:
  ContentRepository:
    contentDimensions:
      language:
        label: Language
        icon: icon-language
        default: de
        defaultPreset: de
        presets:
          all: null
          de:
            label: DE
            values:
              - de
            uriSegment: de
          en_US:
            label: EN
            values:
              - en_US
            uriSegment: en
      mautic:
        label: 'Mautic Segment'
        icon: 'icon-globe'
        default: defaultUser
        defaultPreset: defaultUser
        presets:
          all: null
          defaultUser:
            label: 'Default User'
            values:
              - defaultUser
            uriSegment: ''
          testsegment:
            label: Test Segment
            values:
              - testsegment
            uriSegment: ''
```
You can't change between defaultUser and testsegment dimensions in BE. The functions `getAdditionalNodeData` and `flowQuery ` are not executed.

#### Expected behavior

Backend would use Node and not uriSegment to distinct Dimensions.

#### Actual behavior

It doesn't. Instead after loading, it just restores the config and the old page is shown. 

![2019-08-14 11 31 36](https://user-images.githubusercontent.com/13136881/63010738-358ff500-be87-11e9-96a1-c0f991e927ee.gif)

### Affected Versions

Neos: 4.3.3

UI: 3.8.0
