### ISSUE TITLE
Count Validator does not work with a minimum of 1

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-ui#2552]
### Description

The Count validator does not enforce a minimum count of one with an option `minimum: 1`

### Steps to Reproduce

1. Create a NodeType with a countable type (e.g. `references`) and a corresponding count validation (see below)
2. Trigger validation in the Neos backend by removing the last item in the corresponding editor in the inspector

#### Expected behavior

A validation error is displayed

#### Actual behavior

No validation error occurs

### Affected Versions

2.0+ (see https://github.com/neos/neos-ui/commit/0613b5c205477c08cc2f89388e5f779afd4cb825)

### Example Node Type

```yaml
'Some.Node:Type':
  properties:
    'test':
      type: array
      validation:
        'Neos.Neos/Validation/CountValidator':
          minimum: 1
      ui:
        label: 'Validator test'
        inspector:
          group: 'document'
          editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
          editorOptions:
            allowEmpty: true
            placeholder: 'Select Options'
            values:
              'foo':
                label: 'Foo'
              'bar':
                label: 'Bar'
              'baz':
                label: 'Baz'
```

### Background

I assume that the regression was introduced with this 0-check: https://github.com/neos/neos-ui/blob/master/packages/neos-ui-validators/src/Count/index.tsx#L35-L37

The ["old" CountValidator](https://github.com/neos/neos/blob/master/Resources/Public/JavaScript/Shared/Validation/CountValidator.js) didn't have such check.

When removing the check, an error is displayed: `The count must be between 1 and NaN.`
..I think we need multiple l18n labels here, like done with the `stringLength` validation errors

**Comment by bwaidelich** [comment]
Sorry for the fuzz, the issue can be worked around using the `NotEmpty` validator of course:
```yaml
      validation:
        'Neos.Neos/Validation/NotEmptyValidator': []
        'Neos.Neos/Validation/CountValidator':
          minimum: 1
          maximum: 3
```
