### ISSUE TITLE
SelectBoxEditor with ModelDataSource cannot be set to "null"

### ISSUE THREAD

**Issue by bweinzierl** [neos/neos-ui#2553]
### Description

When using the SelectBoxEditor with a implementation of AbstractModelDataSource like it is the default for type `Neos\Media\Domain\Model\Tag` the selected option cannot be unselected again after the changes where applied (see screencast).

### Steps to Reproduce

1. Configure Nodetype with a tag property:
```
filterTag:
      type: 'Neos\Media\Domain\Model\Tag'
      defaultValue: null
      ui:
        label: 'Filter by Tag'
        reloadIfChanged: TRUE
        inspector:
          group: 'filterOptions'
          position: 30
          editorOptions:
            dataSourceAdditionalData:
              firstEmpty: true
```
2. Select a Tag in the backend and apply changes 
3. Try to deselect the tag again

#### Expected behavior

It should be possible to deselect the option / select a null value

#### Actual behavior

It switches back to the currently saved option. So the property cannot be set to `null` again.

[Screencast from Slack Channel](https://neos-project.slack.com/files/U050FRJ0S/FMV9ZCSSW/screen_recording_2019-09-11_at_09.22.35.mov)

### Affected Versions

Neos: 
4.3.4 

UI:
3.8.1
