### ISSUE TITLE
SCSS code in CSS file

### ISSUE THREAD

**Issue by markuspfeifenberger** [neos/neos-ui#2625]
### Description

In the file packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/style.css SCSS code is used, which may not work here

#### Expected behavior

Use CSS code

UI: 5.0.2

**Comment by markusguenther** [comment]
```css
.toolBar__btnGroup__btn {
    float: left;

    &:hover {
        background-color: var(--colors-PrimaryBlue);
    }

    svg {
        width: 1em;
    }
}
```

Do you mean something like that?
This is not sass code. We use postcss with nesting. This works because of our config in the build-essentials.

```javascript
const styles = require('./styles/styleConstants');
const styleVars = styles.generateCssVarsObject(styles.config);

module.exports = {
    plugins: [
        require('autoprefixer'),
        require('postcss-css-variables')({
            variables: Object.assign(styleVars)
        }),
        require('postcss-import')(),
        require('postcss-nested')(),
        require('postcss-hexrgba')()
    ]
};

```
