### ISSUE TITLE
UriPathSegmentEditor ignores disabled & readonly flag

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-ui#2824]
### Description

The `UriPathSegmentEditor` that was introduced with #2574 ignores the `disabled` and `readonly` [editorOptions](https://neos.readthedocs.io/en/stable/References/PropertyEditorReference.html#property-type-string-textfieldeditor-single-line-text-editor-default)

### Steps to Reproduce

1. Disable the `uriPathSegment` property via `NodeTypes.yaml`:

```yaml
'Neos.Neos:Document':
  properties:
    'uriPathSegment':
      ui:
        inspector:
          editorOptions:
            disabled: true
            # or:
            #readonly: true
```

2. Enter the Neos backend and open up the property inspector for the `uriPathSegment` property of a corresponding document node

#### Expected behavior

Text field for the uriPathSegment cannot be altered via direct input nor via the new synchronize button

#### Actual behavior

The textfield input is protected but it can be changed via the button:

![image](https://user-images.githubusercontent.com/307571/98369060-a4cba900-2038-11eb-9bb6-b25df22c0ee1.png)

![image](https://user-images.githubusercontent.com/307571/98369067-a85f3000-2038-11eb-9b5d-8bca72b0db0a.png)

### Affected Versions

UI: 5.1.0+
