### ISSUE TITLE
No test to the nodetype help messages

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#2825]
### Description

It is possible to configure nodetypes with a little helper message to describe the user what the nodetype is used for.
The bonus is that you are allowed to use markdown for the help message.

```
ui:
    label: Headline_Test
    icon: icon-header
    position: 200
    inlineEditable: true
    help:
      message: 'Markdown **test**.'
```

As we update the library from time to time we should also have a little test for that.
https://github.com/neos/neos-ui/pull/2823
