### ISSUE TITLE
Validation is no longer enforced for inline editable properties

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-ui#2828]
### Description

Since #2538 validation could be activated for inline editable properties.
Due to some regression this no longer works with Neos 5.0+

### Steps to Reproduce

Adjust the headline node type definition in the demo site:

```yaml
'Neos.Demo:Content.Headline':
  properties:
    'title':
      # ...
      validation:
        'Neos.Neos/Validation/StringLengthValidator':
          minimum: 1
          maximum: 5
```

Open up the homepage (or any other page that contains a headline node) and enter a headline that exceeds 5 characters

#### Expected behavior

The inline editable should get a red border & display the validation error (see #2538).
It should be impossible to persist / publish the invalid state.

#### Actual behavior

The validation is completely ignored.

### Affected Versions

Neos: 5.0+
UI: 5.1+ (probably also 5.0)

**Comment by markusguenther** [comment]
The neos.ui has a automated test for that and has the nodetype headline.

```
'Neos.TestNodeTypes:Content.Headline':
  superTypes:
    'Neos.Neos:Content': true
  ui:
    label: Headline_Test
    icon: icon-header
    position: 200
    inlineEditable: true
    help:
      message: 'Markdown **test**.'
  properties:
    title:
      type: string
      defaultValue: '<h1>Enter headline here</h1>'
      ui:
        inlineEditable: true
        inline:
          editorOptions:
            placeholder: '<h2>Enter headline here...</h2>'
            formatting:
              h1: true
              h2: true
              h3: true
              h4: true
              h5: true
              a: true
      validation:
        'Neos.Neos/Validation/NotEmptyValidator': []
        'Neos.Neos/Validation/StringLengthValidator':
          minimum: 1
          maximum: 255
```

This leads to the following result.

![Uploading Screenshot 2020-11-16 at 21.18.05.png…]()
