### ISSUE TITLE
Feature Request: Dynamic Placeholders

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-ui#2837]
It would be really nice to have the possibility to create dynamic placeholders like this:

```yaml
'Foo.Bar:Document.Page':
  properties:
    headline:
      ui:
        inline:
          editorOptions:
            placeholder: 'ClientEval:node.properties.title'
```
