### ISSUE TITLE
Enable depending properties in node creation dialog

### ISSUE THREAD

**Issue by theDex** [neos/neos-ui#2852]
You can use depending properties in the property inspector as described in https://docs.neos.io/cms/manual/content-repository/nodetype-properties#depending-properties
This behaviour does not work in the node creation dialog which is only a nuisance if you use it for properties that are later on accessible via the inspector, but a real problem if you want to use these properties in a node creation handler to e. g. create child node depending on which options were chosen before.

### Steps to Reproduce

If I have a config like:
```
My.Package:NodeType:
  properties:
    property:
      type: integer
      ui:
        showInCreationDialog: true
        label: i18n
        inspector:
          group: 'default'
          editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
          editorOptions:
            dataSourceIdentifier: 'data-source-1'
      validation:
        'Neos.Neos/Validation/NotEmptyValidator': []
    otherProperty:
      type: integer
      ui:
        showInCreationDialog: true
        label: i18n
        inspector:
          group: 'default'
          editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
          editorOptions:
            dataSourceIdentifier: 'data-source-2'
            dataSourceAdditionalData:
              argument: 'ClientEval:node.properties.property'
      validation:
        'Neos.Neos/Validation/NotEmptyValidator': []
```
it works in the inspector, but in the node creation dialog the `data-source-2` is called with the string `'ClientEval:node.properties.property'` as `$arguments['argument']` in the beginning and not refreshed, when the first select-box is chosen.

#### Expected behavior

I would expect, that at least the second select box is refreshed, when the first one is chosen. It would be perfect if I could even use sth. like `argument: 'ClientEval:data.anyField'` to use a field that is only defined in `ui.creationDialog.elements` and not saved as a property of the node afterwards. Also hiding elements of the creation dialog until others are chosen like you can do with elements in the inspector as described in https://docs.neos.io/cms/manual/content-repository/nodetype-properties#depending-properties would be nice.

### Tested on Versions

Neos: dev-master

UI: dev-master

Related: #1138
