### ISSUE TITLE
Add ClientEval possibility to startingPoint of inline links

### ISSUE THREAD

**Issue by Benjamin-K** [neos/neos-ui#2885]
### Description

Currently you can set a starting point for links added to inline text. The big problem is, that this link is static. For large sites it would be great to dynamically set the startingPoint to a subset of the website depending on the page type. 

Think of the following page structure:

```
Home (NodeType: The.Site:Document.Home)
|- Project 1 (NodeType: The.Site:Document.ProjectHome)
|  |- Section 1
|  |- Section 2
|  |- Section 3
|  |- Section 4
| - Project 2
|  |- Section 1
|  |- Section 2
|  |- Section 3
|  |- Section 4
| - Project 3
|  |- Section 1
|  ... tbc
```

It would be nice, if the given sites could be limited to the current project because it's really hard to differentiate which section is the correct one. This could be achieved in the LinkEditor in the sidebar by using ClientEval and write the startingPoint anywhere on the page. Something like this:

```
# Fusion part
bodyTag.attributes.data-linkbase = ${q(documentNode).context({'invisibleContentShown': true}).closest('[instanceof The.Site:Document.ProjectHome],[instanceof The.Site:Document.Home]').property('_path')}

# yaml definition
properties:
  link:
    ui:
      inspector:
        editorOptions:
          startingPoint: "ClientEval: document.querySelector('[name=neos-content-main]')?.contentDocument.body.getAttribute('data-linkbase')"
```

To make this work for inline linking, the startingPoint needs to be evaluated, too, which is currently not the case. 

This would also improve the behavior of the link editor itself, as mentioned by @bwaidelich in #2669.

### Steps to Reproduce

1. Update the startingPoint option of any text nodetype to a value with ClientEval: `text.ui.inline.editorOptions.linking.startingPoint: "ClientEval: '/sites'"`
2. Try to add a link in the inline editor
3. See the inline editor being unable to find a link

#### Expected behavior

The startingPoint should be evaluated.

#### Actual behavior

The startingPoint is used as string and therefore doesn't find any node.

### Affected Versions

As this is not implemented yet, it should affect all (UI) versions. Versions tested:

Neos: 5.3, 7.0
UI: 5.3.4, 7.0.0
