### ISSUE TITLE
Backend crashes if no nodes are available

### ISSUE THREAD

**Issue by PRGfx** [neos/neos-ui#2913]
### Description

If a user has no access to a site i.e. through a `NodeTreePrivilege`, the backend can't load any nodes and the UI crashes.

### Steps to Reproduce

1. setup a neos-base-distribution
2. setup "content"
    ```
    ./flow doctrine:migrate
    
    ./flow site:create --node-name site1 --node-type Neos.Demo:Document.Homepage --package-key Neos.Demo --name Site1
    ./flow domain:add --site-node-name site1 --hostname site1.local
    
    ./flow site:create --node-name site2 --node-type Neos.Demo:Document.Homepage --package-key Neos.Demo --name Site2
    ./flow domain:add --site-node-name site2 --hostname site2.local
    
    ./flow user:create admin password Ad Min --roles Neos.Neos:Administrator,Neos.Demo:MyTestEditor2
    ```
3. configure policies
    ```yaml
    privilegeTargets:
      'Neos\Neos\Security\Authorization\Privilege\NodeTreePrivilege':
        'Neos.Demo:MyTestSite1':
          matcher: 'isDescendantNodeOf("/sites/site1")'
        'Neos.Demo:MyTestSite2':
          matcher: 'isDescendantNodeOf("/sites/site2")'
    roles:
      'Neos.Demo:MyTestEditor1':
        parentRoles:
          - 'Neos.Neos:RestrictedEditor'
        privileges:
          -
            privilegeTarget: 'Neos.Demo:MyTestSite1'
            permission: GRANT
      'Neos.Demo:MyTestEditor2':
        parentRoles:
          - 'Neos.Neos:RestrictedEditor'
        privileges:
          -
            privilegeTarget: 'Neos.Demo:MyTestSite2'
            permission: GRANT
    ```
4. visit the backend for Site1 and Site2

#### Expected behavior

Site2 should work fine, but for Site1 the content-module should render some kind of error message that the current site is not available/the user is not allowed to access this backend-module. Maybe if the user has access to other sites, there could be a selection to switch the site.

#### Actual behavior

Site2 works fine, but for Site2 the react app unmounts, resulting in a white screen.

<details>
<summary>stacktrace</summary>

```
TypeError: can't convert null to object
    preprocessViewConfiguration index.js:134
    preprocessViewConfigurationDebounced index.js:158
    Lodash 3
    componentDidUpdate index.js:111
    React 2
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    Redux 4
    e content:1
    clipboardMiddleware clipboardMiddleware.js:10
    localStorageMiddleware localStorageMiddleware.js:13
    Redux 11
    react-dom.production.min.js:209:194
    React 5
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    Redux 4
    e content:1
    clipboardMiddleware clipboardMiddleware.js:10
    localStorageMiddleware localStorageMiddleware.js:13
    Redux 11
```
</details>

### Affected Versions
Tested with the following versions:

Neos: 5.3.0 / 7.1.0

UI: 5.3.4 / 7.1.1
