### ISSUE TITLE
Document Tree indicates children even though none are reachable due to lack of privileges

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#2934]
### Description

Configuring a `NodeTreePrivilege` may lead to all child-documents of a particular document node being unreachable. In that case, the document should not indicate that it has document children and should not offer an uncollapse handle in the document tree component.

Currently, the uncollapse handle is visible and can be triggered - without actually showing any child nodes of course.

### Steps to Reproduce

You'll need at least a NodeTreePrivilege configured to hide all document children of a particular node. An example would be:

```yaml
privilegeTargets:
  'Neos\Neos\Security\Authorization\Privilege\NodeTreePrivilege':
    'Vendor.Site:MyNodeTreePrivilege':
      matcher: 'nodeIsOfType("Vendor.Site:Document.Privileged")'

roles:
  'Neos.Neos:Administrator':
    privileges:
      -
        privilegeTarget: 'Vendor.Site:MyNodeTreePrivilege'
        permission: GRANT
```
(This would hide all nodes of type `Vendor.Site:Document.Privileged`)

Then, you'll need two accounts. One that has the privilege and one that doesn't.

What you'll see is:

|With privilege|Without privilege|
|-|-|
| ![Screenshot_2021-08-01_12-29-23](https://user-images.githubusercontent.com/2522299/127768025-ff4ee0d8-383b-483a-8af7-cd4e284a28a4.png) | ![Screenshot_2021-08-01_12-28-50](https://user-images.githubusercontent.com/2522299/127768028-87f2ef70-abc7-4189-b49b-ae4a2bd43c25.png) |

#### Expected behavior

![Screenshot_2021-08-01_12-28-50-should](https://user-images.githubusercontent.com/2522299/127768061-b90aecb9-8686-4dec-8c16-52808a889f5f.png)

A document in the document tree component that has no reachable children should not indicate that it has children and should not offer an uncollapse handle.

#### Actual behavior

![Screenshot_2021-08-01_12-28-50](https://user-images.githubusercontent.com/2522299/127768067-619e43c4-a865-469e-bba6-6dba5c9620df.png)

The uncollapse handle is visible and can be triggered.

### Affected Versions

Neos: all
UI: all
