### ISSUE TITLE
CodeMirror highlightingMode is lost

### ISSUE THREAD

**Issue by PRGfx** [neos/neos-ui#2959]
### Description
The `highlightingMode` editor-option for the `CodeEditor` doesn't get passed down to the final component.

### Steps to Reproduce
Use the CodeEditor and set it to a different highlighting mode:
```yaml
    code:
      type: string
      ui:
        label: Code
        inspector:
          group: document
          editor: Neos.Neos/Inspector/Editors/CodeEditor
          editorOptions:
            highlightingMode: text/javascript
```

#### Expected behavior
The editor should highlight with JS syntax.

#### Actual behavior
The `CodeMirror` editor receives `options.highlightingMode`:
![Screenshot react dev-tools showing actual values of highlightingMode and options.highlightingMode](https://user-images.githubusercontent.com/3868790/136404188-abdd6fad-3225-4c45-8488-b0309fe1465b.png)
but passes on `props.highlightingMode` (rather than `props.options.highlightingMode`), which is initialized to `"htmlmixed"`:
https://github.com/neos/neos-ui/blob/c7bbe1d6db187827df252e562c9611ec7754169a/packages/neos-ui-editors/src/Editors/CodeMirror/index.js#L61

### Affected Versions

Neos: found in 7.1 but seems to be there for a long time
