### ISSUE TITLE
BUG: DataSources dont work without dataSourceUri

### ISSUE THREAD

**Issue by gjwnc** [neos/neos-ui#2984]
### Description

To get a list of entries for a SelectBox using a DataSource the endpoint URL is relative like
`/neos/service/data-source/{dataSourceIdentifier}`. I think, this URL is then used [here](https://github.com/neos/neos-ui/blob/master/packages/utils-helpers/src/urlWithParams.ts#L9).

Since this is a relative URL, the URL() constructor needs a baseurl as the second parameter [see here](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL). Currently this throws a `TypeError`.

In Firefox, the NEOS Backend shows the error
```
TypeError: URL constructor: /neos/service/data-source/webcoicon is not a valid URL.
```
in the Inspektor where the DataSource should have been rendered.

### Workaround

A workaround is, to set the `dataSourceUri` property in the NodeType definition like
```
        inspector:
          editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
          editorOptions:
            placeholder: 'Choose icon'
            dataSourceIdentifier: 'webco-icon'
            dataSourceUri: 'http://some.domain/neos/service/data-source/webcoicon'
```

### Steps to Reproduce

1. Select a content node which uses a DataSource with dataSourceIdentifier
2. The Browser shows an error where the DataSource should have been rendered in the Inspector

#### Expected behavior

Correctly render the DataSource Node property.

#### Actual behavior

![image](https://user-images.githubusercontent.com/19683930/141745828-60d14527-64f7-4ae4-8794-bae7640102f3.png)

### Affected Versions

I think, this is related to [this](https://github.com/neos/neos-ui/commit/b07e952b872bf19d442a4988c827b3b5baef9868#diff-fda5ab1090f815776dac7d8fe940492dfe8905dcb8b5630490c7a230a636dfc4) commit, thus:

Neos:

UI: >= 5.3.3
