### ISSUE TITLE
Bug: NumberRangeValidator fails when Text is added after a valid number

### ISSUE THREAD

**Issue by paavo** [neos/neos-ui#3015]
### Description
NumberRangeValidator fails when a Character like `2000a` is added after a valid number ex. `2000`

### Steps to Reproduce
1. Add a valid value (ex. `2000`)
2. Add an invalid character to the number (ex. `2000a`)
3. The ui-validator is still valid, but the property didn't get persited

#### Expected behavior
`2000a` should be not pass the validation

#### Actual behavior
`2000a` passed the validation
`a2000` do not pass the validation

### Affected Versions

Neos: 5.3
UI: 5.3.13

### NodeType to debug
```
'Vendor.NodeTypes.Foo:Content.History.Event':
  superTypes:
    'Neos.Neos:Content': true
  ui:
  properties:
    year:
      type: integer
      ui:
        label: Jahr
        reloadIfChanged: true
        showInCreationDialog: true
      validation:
        'Neos.Neos/Validation/NotEmptyValidator':
        'Neos.Neos/Validation/NumberRangeValidator':
          minimum: 1000
          maximum: 3000
```
