### ISSUE TITLE
BUG: Option with value 0 in selectbox 

### ISSUE THREAD

**Issue by pKallert** [neos/neos-ui#3070]
### Description
After adding a SelectBoxEditor with one of the value 0, the label is not shown when the option is active. Instead 'Choose'  is shown 

### Steps to Reproduce

1. Add a new property: 

```yaml
autoplay:
      type: integer
      defaultValue: ''
      ui:
        label: 'Autoplay'
        reloadPageIfChanged: true
        inspector:
          group: 'image'
          editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
          editorOptions:
            values:
              '0':
                label: 'No Autoplay'
              '1000':
                label: '1 Second'
```
2. Chose 'No Autoplay' as the active option in the dropdown 
3. Click 'Apply'
#### Expected behavior
The label for the value 0 ('No Autoplay') is shown as active. 

#### Actual behavior
The label is not shown and instead the 'Chose' placeholder is shown: 

https://user-images.githubusercontent.com/91674611/157833078-48949e8a-717d-4424-85dc-8eb3ac45ef3f.mov

### Affected Versions

UI: 5.3
