### ISSUE TITLE
Login dialog should be shown across tabs

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-ui#3142]

**Comment by mhsdesign** [comment]
this is still an issue with UI version: v7.0.3

you can test it like this:

```yaml
Neos:
  Flow:
    session:
      inactivityTimeout: 10
```

then wait a bit and navigate to another document-node
