### ISSUE TITLE
Help message translation is only visible if you click on the question mark

### ISSUE THREAD

**Issue by crydotsnake** [neos/neos-ui#3172]
### Description

If you add a `help` message translation with `i18n` to your NodeType, the translation only gets visible if you click on the question mark in your NodeType. But if you hover over the NodeType, you see the full path to your translation.

But if you change the `i18n` in your NodeType to a string, the translation will show up if you hover over your NodeType, and when clicking on the question mark

### Steps to Reproduce

1. Add a help message with a translation to your NodeType:

```yaml
'Vendor.Package:Content.Video':
  ui:
    help:
      message: i18n
```
	
2. Hover over your NodeType, and click the question mark.

3. Change your `message:` to a string:

```yaml
'Vendor.Package:Content.Video':
  ui:
    help:
      message: 'My helpful help message'
```
and hover over your NodeType, and click the question mark.

#### Expected behavior

If you define a help message translation with `i18n` the translations should show up in both cases.

#### Actual behavior

The help message translation doesent show up in both cases.

![2022-08-18 20-18-32 2022-08-18 20_20_31](https://user-images.githubusercontent.com/39345336/185466999-14710615-3ad6-4692-9790-8bb281757ef4.gif)

### Affected Versions

Neos: All

UI: 7.3.6
