### ISSUE TITLE
BUG: React Warning: Failed prop type: The prop `icon` is marked as required in `DimensionSelector`, but its value is `undefined`.

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#3313]
### Description

Given you have a dimension configuration containing dimensions without configured icons, the `DimensionSelector` causes React to issue the following warning:

> Warning: Failed prop type: The prop `icon` is marked as required in `DimensionSelector`, but its value is `undefined`.
>     in DimensionSelector (created by Context.Consumer)
>     in Neos(DimensionSelector) (created by DimensionSwitcher)
>     in ul (created by _ShallowDropDownContents)
>     in _ShallowDropDownContents (created by ContextDropDownContents)
>     in ContextDropDownContents (created by ThemedContextDropDownContents)
>     in ThemedContextDropDownContents (created by StatelessDropDownWrapperWithoutClickOutsideBehavior)
>     in div (created by StatelessDropDownWrapperWithoutClickOutsideBehavior)
>     in StatelessDropDownWrapperWithoutClickOutsideBehavior (created by clickOutside(StatelessDropDownWrapperWithoutClickOutsideBehavior))
>     in clickOutside(StatelessDropDownWrapperWithoutClickOutsideBehavior) (created by ThemedclickOutside(StatelessDropDownWrapperWithoutClickOutsideBehavior))
>     in ThemedclickOutside(StatelessDropDownWrapperWithoutClickOutsideBehavior) (created by DimensionSwitcher)
>     in DimensionSwitcher (created by Context.Consumer)
>     in Neos(DimensionSwitcher) (created by ConnectFunction)
>     in ConnectFunction (created by PrimaryToolbar)
>     in div (created by PrimaryToolbar)
>     in div (created by Bar)
>     in Bar (created by ThemedBar)
>     in ThemedBar (created by PrimaryToolbar)
>     in PrimaryToolbar (created by ConnectFunction)
>     in ConnectFunction (created by Context.Consumer)
>     in Neos(Connect(PrimaryToolbar)) (created by App)
>     in div (created by App)
>     in App (created by ConnectFunction)
>     in ConnectFunction (created by Root)
>     in Neos (created by Root)
>     in Unknown (created by Root)
>     in Provider (created by Root)
>     in div (created by Root)
>     in Root [checkPropTypes.js:20:14](https://temp-repro.ddev.site/_Resources/Static/node_modules/prop-types/checkPropTypes.js)

### Steps to Reproduce

1. Make sure you have a Neos installation with a dimension configuration, like:
  ```yaml
  Neos:
    ContentRepository:
      contentDimensions:
        language:
          icon: icon-globe
          label: 'Language'
          default: en_US
  ``` 
3. Comment out the icon configuration for one of the dimensions:
  ```yaml
  Neos:
    ContentRepository:
      contentDimensions:
        language:
          # icon: icon-globe
          label: 'Language'
          default: en_US
  ``` 
5. Open the DimensionSelector in the Neos UI
6. See error in the console

#### Expected behavior

There should be no warning/error.

#### Actual behavior

![image](https://user-images.githubusercontent.com/2522299/209675929-cecbfca8-7418-455f-a8d7-8ab950f0850e.png)

### Affected Versions

Neos: 8.2

UI: 8.3 (verified, 8.2 and below do not show the warning)
