### ISSUE TITLE
BUG: CreationDialog shows invalid date with string now as value

### ISSUE THREAD

**Issue by ghost** [neos/neos-ui#3391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a property with datetime and default value now is shown in creation dialog it shows the error invalid date but once you create the page it shows the correct date in the inspector.

```yaml
    publicationDate:
      type: DateTime
      defaultValue: 'now'
      ui:
        showInCreationDialog: true
```

### Expected Behavior

Shows current date in creation dialog

### Steps To Reproduce

- create a datetime property
- set defaultvalue to now
- set showInCreationDialog to true

### Environment

```markdown
- Flow: 8.1.2 
- Neos: 8.1.2
- PHP: 8.1
```
