### ISSUE TITLE
DISCUSSION: Make css grid area identifiers public again?

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-ui#3450]
### Description

With 8.2 we switched to css grid
With https://github.com/neos/neos-ui/pull/3366 (unreleased 8.3) the css grid identifiers declared here:
https://github.com/neos/neos-ui/blob/e4080d6bb1a14a2c5eb843109ee82af38b84c8cf/packages/neos-ui/src/Containers/style.module.css#L8
will be scoped to the css module (and the are name will obscurified)
thats why we use composition to apply the grid-area property: https://github.com/neos/neos-ui/blob/e4080d6bb1a14a2c5eb843109ee82af38b84c8cf/packages/neos-ui/src/Containers/RightSideBar/style.module.css#L2
https://github.com/neos/neos-ui/blob/e4080d6bb1a14a2c5eb843109ee82af38b84c8cf/packages/neos-ui/src/Containers/style.module.css#L24

as proposed here: https://github.com/parcel-bundler/lightningcss/issues/144#issuecomment-1091821622

## Fyi, there is now an proposal in css-modules for global css grid identifier:

https://github.com/css-modules/css-modules/issues/390

**Comment by Sebobo** [comment]
I had a similar issue in the media ui and when putting the areas and references into css variables, it works and keeps the names intact.

Which is actually even nicer for extensibility.

Example:

```css
.container {
    --grid-areas: "left top right" "left main right";
    --grid-area-right: right;
    grid-template-areas: var(--grid-areas);
}

.gridRight {
    grid-area: var(--grid-area-right);
}
```

**Comment by mhsdesign** [comment]
nice trick ^^ (makes sense that you had the same problem as youre also using parcels lightning css under the hood?)

so yes im fine with implementing it like this.


otherwise we could also do:

some global css file:
```css
.my-css-grid {
    grid-template-areas: "left top right" "left main right";
}

.my-css-grid-right {
  grid-area: right;
}
```


```css
.container {
    composes: my-css-grid from global;
}
.gridRight {
    composes: my-css-grid-right from global;
}
```
