### ISSUE TITLE
BUG: Disabled SelectBoxEditor Multiselect has "remove" not disabled

### ISSUE THREAD

**Issue by sbruggmann** [neos/neos-ui#3493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Already existing items in a SelectBoxEditor with `multiple: true` (if type is an array) and `disabled: true` can get removed:

[Screencast from 05.05.2023 21:09:09.webm](https://user-images.githubusercontent.com/1162368/236550178-2c777e8d-2081-4358-9127-a2b9267b4f47.webm)

### Expected Behavior

Items can not be removed.

### Steps To Reproduce

Add an item to a Multiselect SelectBoxEditor:
```yaml
    demo:
      type: array
      ui:
        label: Demo
        inspector:
          group: 'settings'
          editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
          editorOptions:
            values:
              a:
                label: A
              b:
                label: B
            # disabled: true
```

Disable the property:
```yaml
    demo:
      ui:
        inspector:
          editorOptions:
            disabled: true
```

### Environment

```markdown
Tested starting with Neos 7.1, 8.1 and 8.3
```
