### ISSUE TITLE
BUG: `RangeEditor` does not respond to discard action

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#3500]
### Description

The `RangeEditor` keeps its value when the user hits the "discard" button at the bottom of the inspector.

### Steps to Reproduce
1. Configure a node type with a property that can be edited via `RangeEditor`, e.g.:
```yaml
'Vendor.Site:MyContentNode':
  # ...

  properties:
    rangeEditorExample:
      type: integer
      ui:
        label: 'RangeEditor Example'
        reloadIfChanged: true
        help:
          message: >
            This is a Range editor example.
        inspector:
          group: examples
          editor: 'Neos.Neos/Inspector/Editors/RangeEditor'
          editorOptions:
            minLabel: Invisible
            maxLabel: Opaque
            min: 0
            max: 100
            step: 5
            unit: px
```
2. Create/Edit such a node in the UI
3. Change the value via the range slider
4. Click on "Discard"
5. Notice that the value of the `RangeEditor` has not been reset

#### Expected behavior

If the value of a `RangeEditor` inside the inspector has been changed, hitting "discard" resets this value.

*Example: The `TextFieldEditor`*

https://github.com/neos/neos-ui/assets/2522299/a2df3c6f-b40a-42e1-9f16-73157dd88559

#### Actual behavior

https://github.com/neos/neos-ui/assets/2522299/57a73af7-926f-47e9-89c1-b0db20f1f3ce

### Affected Versions

Neos: >= 7.3

UI: >= 7.3
