### ISSUE TITLE
BUG: `title` label changes in node not reflected in creationDialog

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-ui#3509]
if you have a node with the following config (to override the label name of the title)

```yaml
Foo.Bar:NodeType:
  superTypes:
    Neos.Neos:Document: true
  title:
    ui:
      label: "hello"
```

it will still show the translated label "Title" in the creation dialog, and in the inspector the correct label "hello"

to have the wanted effect, we need to specify it explicitly:

```yaml
Foo.Bar:NodeType:
  superTypes:
    Neos.Neos:Document: true
  ui:
    creationDialog:
      elements:
       title:
         ui:
           label: "hello"
  title:
    ui:
      label: "hello"
```

to understand why i dug deeper:

In Neos.Neos properties.title.label is set to `i18n` in 
https://github.com/neos/neos-development-collection/blob/ef5c5738550774d32f591dffcf87f799f0d54fde/Neos.Neos/Configuration/NodeTypes.Document.yaml#L45
(this we want to override)

when showInCreationDialog is set to true, the i18n will still contain the translation path which is equal to the one from when its used as property: `Neos.Neos:NodeTypes.Document:properties.title`
(as the label generation is done before the postprocessors are applied: https://github.com/neos/neos-development-collection/issues/2867)

in Neos.Neos.Ui we specify as title label as `i18n` [here](https://github.com/neos/neos-ui/blob/f2d18d59c3dafa0a9a69a8eff95550c0898f503e/Configuration/NodeTypes.yaml#L9), i think, so it can be targeted with a different translation (even though the translation lies in Neos.Neos https://github.com/neos/neos-development-collection/blob/ef5c5738550774d32f591dffcf87f799f0d54fde/Neos.Neos/Resources/Private/Translations/en/NodeTypes/Document.xlf#L17) and the translation is the same: "Title"

Due to the explicit specification in Neos.Neos.Ui it seems logically why we need to override this one too, but it is at least counter intuitive.

If there are more people expecting the behaviour like me than people expecting to be able to override the translation
`creationDialog.title` i think we should remove the line https://github.com/neos/neos-ui/blob/f2d18d59c3dafa0a9a69a8eff95550c0898f503e/Configuration/NodeTypes.yaml#L9 and with it the additional translation.
