### ISSUE TITLE
BUG: Select Box show as empty when current value doesnt match anymore the values

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-ui#3520]
Currently a mismatch from datasource to current value will be displayed falsely as being empty. We should make it obvious that the value didnt match.

## Simple reproduction

have a selectbox option with defined values:

```yaml
tagName:
  type: string
  defaultValue: 'h2'
  ui:
    label: i18n
    reloadIfChanged: true
    inspector:
      group: settings
      position: 10
      editor: Neos.Neos/Inspector/Editors/SelectBoxEditor
      editorOptions:
        values:
          h1:
            label: h1
          h2:
            label: h2
          h3:
            label: h3
          h4:
            label: h4
          h5:
            label: h5
```

set it to for example to h5 in the ui and then change the node type to remove the option.
Reload the ui and see this:

<img width="314" alt="image" src="https://github.com/neos/neos-ui/assets/85400359/61870994-c606-459c-a168-3a7d8ac700dc">

it seems the property is not set at all, but you are mistaken it is just shown as empty. Additionally a not empty validator wouldnt complain as the property is actually not empty.

This behaviour should be improved.

A similar buggy behaviour also exists for selectboxes with `allowEmpty: true`
after the above steps a mismatch is also being shown as empty but one still has the `X` delete button, which gives a hint that its not really empty after all.

<img width="297" alt="image" src="https://github.com/neos/neos-ui/assets/85400359/9e643faf-d526-4f29-9066-337d1f996c8d">

And the same for `multiple: true`

<img width="298" alt="image" src="https://github.com/neos/neos-ui/assets/85400359/c5bd374a-a347-4283-a933-2f0a5a2aaabe">

when adding a new element in `multiple: true` it behaves buggy when deleting one item as its stays after the first click (one deletes the empty value or something)
