### ISSUE TITLE
Value 0 is not shown in RangeSlider

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-ui#3598]
If it is possible to set a value to `0`, the number `0` is not shown in the input field.

https://github.com/neos/neos-ui/assets/4510166/f60b5da8-e3ec-4a46-894e-90a1b8effe08

```yaml
value:
      type: integer
      defaultValue: 0
      ui:
        inspector:
          editor: 'Neos.Neos/Inspector/Editors/RangeEditor'
          editorOptions:
            min: -100
            max: 100
            step: 1
            unit: '%'
```

### Affected Versions

Neos: 8.3.4

UI: 8.3.3
