### ISSUE TITLE
BUG: reference type in creation dialog doesn't work

### ISSUE THREAD

**Issue by tellenrieder** [neos/neos-ui#3615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Using a property with `reference` type in the creation dialog in Neos 9 does not create the module and shows a red popup message with 
`Given property "myProperty" is declared as "reference" in node type "My.Site:Foo.Bar" and must be treated as such.`
The selection of a page in the CD works as desired.

YAML
```   
    myProperty:
      type: reference
      ui:
        label: 'My Reference Property'
        showInCreationDialog: true
        inspector:
          editor: 'Neos.Neos/Inspector/Editors/ReferenceEditor'
          editorOptions:
            nodeTypes: [ 'My.Site:Document.Page ]
      validation:
        Neos.Neos/Validation/NotEmptyValidator: {}
```

### Steps to Reproduce

1. define a property of the `reference` type with `showInCreationDialog: true`
2. create the module in Neos and select a page
3. click 'Create New'

#### Expected behavior

- module is created with the correct selected page as value for this property

#### Actual behavior

- module isn't created
- error popup appears

### Affected Versions

Neos 9 (not sure if the bug appeared since Neos 9 or even earlier)
PHP 8.2

neos/neos-ui - 9.0.x-dev 684bb2f
neos/neos-ui-compiled -  9.0.x-dev 9115a2e

Relates: neos/neos-development-collection#4549
