### ISSUE TITLE
Handle `reloadIfChanged` node type property configuration

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#363]
As for the current architecure, we need server feedback, that in case `reloadIfChanged` is set to true for a changed property, re-renders the respective node via typoscript and delivers the rendering result back to the client.

On client side we need a server feedback handler, that takes care of re-rendering the respective DOM node.

**Comment by skurfuerst** [comment]
implemented.

**Comment by grebaldi** [comment]
I have looked into it again. What implementation currently does is semantically similar to `reloadDocumentIfChanged`.

We could keep it like this for starters, but would need to implement `reloadDocumentIfChanged` as well. 

But I think, it is feasibe to implement `reloadIfChanged` semantically correct for the alpha, so I reopen this.

**Comment by skurfuerst** [comment]
ah good point actually :)

**Comment by skurfuerst** [comment]
not marking it as required for 1.0.0, as the page reload helps for the editor.

**Comment by dimaip** [comment]
Sorry, I don't understand the discussion here. What is `reloadDocumentIfChanged`? Never heard of this config. What's wrong with current implementation of `reloadIfChanged`?

**Comment by dimaip** [comment]
Should it only work with nodes inside content collections, or also with nodes that are direct childNodes of a document node?

**Comment by daniellienert** [comment]
Hey guys, 

according to the documentation, the keywords are: `reloadIfChanged` and `reloadPageIfChanged`, none of both seem to work in the current master. Can someone confirm this?

**Comment by sorenmalling** [comment]
I can confirm that the issue is still present - changing a value and clicking "apply" doesn't reload the content and present the changes.

**Comment by sorenmalling** [comment]
A followup comment:

when the client changes a image or any property with `reloadIfChanged` set to `true` and click the “Apply” button, the content is not being reloaded and they report that the interface doesn’t work. A full page refresh shows the changes as they expect

**Comment by dfeyer** [comment]
I confirm both (reloadIfChanged and reloadPageIfChanged) are not working, try to push it in the next release.

**Comment by dimaip** [comment]
will take care

**Comment by dimaip** [comment]
@dfeyer @sorenmalling weird, just tested with this config from the demo site, and it seems to reload...
```
'Neos.NodeTypes:Image':
  properties:
    imageStyle:
      type: string
      ui:
        label: 'Image style'
        reloadIfChanged: true
        inspector:
          group: image
          position: 55
          editor: Neos.Neos/Inspector/Editors/SelectBoxEditor
          editorOptions:
            values:
              '':
                label: 'None'
              thumbnail:
                label: 'Thumbnail'
```
