### ISSUE TITLE
Date picker is one day off

### ISSUE THREAD

**Issue by Discostu36** [neos/neos-ui#3630]
### Description

I have a date picker for an article:

```yaml
    'publishingDate':
      type: DateTime
      defaultValue: 'today midnight'
      ui:
        label: 'Veröffentlichungs-Datum'
        inspector:
          group: 'ah'
          editorOptions:
            format: 'd.m.Y'
```

But it doesn't work correctly, the date is always one day off.

Unfortunately, I don't know in which version this bug first appeared.

### Steps to Reproduce

1. Add a date property to a configuration yaml
2. Select a date with the date time picker in Neos CMS

#### Expected behavior

The date picked matches the date selected.

#### Actual behavior

The date is always one day off. So, for example, if I click on August 10th, the value is set to August 11th.

![image](https://github.com/neos/neos-ui/assets/30999326/e8de9dbe-cb5e-4323-aa1b-ee4a32830400)

![image](https://github.com/neos/neos-ui/assets/30999326/fce4dedd-8a62-4631-b84b-bde857c5e878)

### Affected Versions

Neos: 8.0.2

UI: 8.0.1
