### ISSUE TITLE
Negative values in RangeEditor get cut off

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-ui#3648]
### Description

A negative value in the RangeEditor get's cut off. When you have a minimal value of 0 and high negative number as min, it is even worse, as only the `max` option is taken into considering on how long the input field should be

### Steps to Reproduce

Create a property like this

```yaml
propertyName:
  type: integer
  ui:
    label: Possible negative Value
    inspector:
      editor: 'Neos.Neos/Inspector/Editors/RangeEditor'
      editorOptions:
        min: -80
        max: 80
        step: 1
        unit: px
```

Try to set a negative value

#### Expected behavior

The value is still fully visible

#### Actual behavior

<img width="436" alt="image" src="https://github.com/neos/neos-ui/assets/4510166/70eba58a-f211-4b78-a4d3-6bd3c4b716cf">

### Affected Versions

Neos: 8.3.6  
UI: 8.3.4
