### ISSUE TITLE
Range editor doesn't support steps below 1

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-ui#3650]
### Description

If you have a property set with the RangeEditor and set the step below 1 (e.g. 0.1) the range editor will still use step 1. Also it isn't possible the use floats as min or max values

```yaml
property:
      type: float
      ui:
        inspector:
          editor: 'Neos.Neos/Inspector/Editors/RangeEditor'
          editorOptions:
            min: -50
            max: 50
            step: 0.1
```

### Affected Versions

Neos: 8.3.6  
UI: 8.3.4
