### ISSUE TITLE
Non-scrollable Neos.Neos/Inspector/Editors/RichTextEditor

### ISSUE THREAD

**Issue by auwaerter** [neos/neos-ui#3664]
### Description

Within my Neos instance the [Neos.Neos/Inspector/Editors/RichTextEditor](https://neos.readthedocs.io/en/stable/References/PropertyEditorReference.html#property-type-string-richtexteditor-full-screen-rich-text-editor) seems to be non-scrollable when i'm having words in an amount that overlaps the browser window. 

I'm using the following workaround(s) to apply changes:
- Click outside of the RichTextEditor, e.g. to another item within the Content Tree. This gives you the "You still have changes. What do you want to do with them?" dialog, where you can "Throw away" or "Apply" your modifications.
- Move down with the arrow down key, but for that you barley can click at the Discard/Apply button, as only 1/4 of it is shown.

I'm using the following NodeType definition (same as the link above):

```yaml
'Super.Vendor:Content.Text':
  superTypes:
    'Neos.Neos:Content': true
    'Super.Vendor:Constraint.Content.Carousel': true
    'Super.Vendor:Constraint.Content.Column': true
    'Super.Vendor:Constraint.Content.Main': true
    'Super.Vendor:Constraint.Content.Teaser': true
    'Super.Vendor:Constraint.Content.Footer': true
  ui:
    label: i18n
    icon: file-text
    position: 20
    inspector:
      groups:
        settings:
          label: 'Settings'
  properties:
    'source':
      type: 'string'
      ui:
        label: 'Toggle the editor'
        reloadIfChanged: true
        inspector:
          group: 'settings'
          editor: 'Neos.Neos/Inspector/Editors/RichTextEditor'
          editorOptions:
            placeholder: '<p>Text</p>'
            autoparagraph: true
            linking:
              anchor: true
              title: true
              relNofollow: true
              targetBlank: true
              download: true
            formatting:
              strong: true
              em: true
              u: true
              sub: true
              sup: true
              del: true
              p: true
              h1: true
              h2: true
              h3: true
              h4: true
              h5: true
              h6: true
              pre: true
              underline: true
              strikethrough: true
              removeFormat: true
              left: true
              right: true
              center: true
              justify: true
              table: true
              ol: true
              ul: true
              a: true
```

Question: Is this a bug or a mistake (in e.g. the editorOptions, where it configures the non-scrolling part) i've did somewhere?

### Steps to Reproduce

1. Use Google Chrome Version 119.0.6045.124
2. Create a new page that includes the 'Super.Vendor:Content.Text' NodeType, which contains the `'Neos.Neos/Inspector/Editors/RichTextEditor'` using the above properties.
3. Navigate to it and add Text using "Toggle the editor".
4. Add 1000 Words generated by https://www.loremipsum.de, copy and paste them into the RichTextEditor.
5. Apply (you already notice, that you can't scroll up to edit the content or e.g. select some properties)
6. Enter again, to "Toggle the editor" (you can't scroll down, but you can use the arrow up/down key)

#### Expected behavior

Scrolling is possible to Apply the changes in the RichTextEditor.

#### Actual behavior
![content_text_nodetype](https://github.com/neos/neos-ui/assets/6923945/50dfcd2c-1c84-4602-bb6c-86630c008ac9)
![toggle_editor](https://github.com/neos/neos-ui/assets/6923945/0a4c9bd1-6d79-46fe-ad33-36dc873e3249)
![scroll_down_with_arrow_keys2](https://github.com/neos/neos-ui/assets/6923945/59c91538-4a18-4b77-b5b7-c4f0438d5ec4)

### Affected Versions

Neos: 8.3.6

UI: 8.3.4
