### ISSUE TITLE
Neos 9.0 Either reimplement or fully remove `presetBaseNodeType`

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-ui#3702]
currently this feature is broken see https://neos-project.slack.com/archives/C0L41E268/p1698743660587269

basti wrote on slack

> Well, partly.. If a different preset is selected, the tree doesn't work anymore – but that can be fixed in UI I assume.

```
Neos:
  Neos:
    userInterface:
      navigateComponent:
        nodeTree:
          loadingDepth: 2
          presets:
            default:
              baseNodeType: 'Neos.Demo:Document.Blog,Neos.Demo:Document.BlogPosting'
            'not blog':
              ui:
                label: 'Not Blog'
                icon: 'icon-book'
              baseNodeType: '!Neos.Demo:Document.Blog,!Neos.Demo:Document.BlogPosting'
```

> Well, partly.. If a different preset is selected, the tree doesn't work anymore – but that can be fixed in UI I assume.

![image](https://github.com/user-attachments/assets/70173d8b-1a0a-4f81-9568-49075ace822d)
