### ISSUE TITLE
FEATURE: Change order of fields in creation dialog (showInCreationDialog)

### ISSUE THREAD

**Issue by dkoether** [neos/neos-ui#3709]
### Is there an existing issue for this topic?

- [X] I have searched the existing issues

### Description

Properties can have the same label like `Title` (e.g. page title, Google Scholar title, meta tag title and Twitter Card title). The editor can differentiate these fields with same name because of their groups in the UI. In the creation dialog we dont have these groups and the editors do not know what kind of title they are filling. So I have to add a suffix like `Title (Google Scholar)` or `Title (Page)`. 

When I overwrite the label with `XYZ.Site:Mixin.Article.A.ui.creationDialog.propertyA.ui.label: 'XYZ.Site:Mixin.Article.A.Labels:properties.propertyA.creationDialog'` I can add this suffix but now the field is moved to the top of the creation dialog. The properties of `XYZ.Site:Mixin.Article.B` are less important and I dont want them on top but still in the creation dialog.

### Example

This is my document nodeType:
```
XYZ.Site:Document.Abstract.Article:
  superTypes:
    XYZ.Site:Mixin.Article.A: true
    XYZ.Site:Mixin.Article.B: true
   [...]
```

Mixins:
```
XYZ.Site:Mixin.Article.A:
  properties:
    propertyA1:
      [...]
    propertyA2:
      [...]
    propertyA3:
      [...]
```

```
XYZ.Site:Mixin.Article.B:
  ui:
    creationDialog:
      elements:
        propertyB1:
          ui:
            label: 'property B1 (label for creation dialog)'
        propertyB2:
          ui:
            label: 'property B2 (label for creation dialog)'
        propertyB3:
          ui:
            label: 'property B3 (label for creation dialog)'
  properties:
    propertyB1:
      [...]
    propertyB2:
      [...]
    propertyB3:
      [...]
```

**Result:**
<img width="958" alt="grafik" src="https://github.com/neos/neos-ui/assets/7765498/e6f503ee-dc5a-4f91-9742-1ab2de9546bf">

To rearrange the fields again I need to define labels also for the properties of `XYZ.Site:Mixin.Article.A`:

```
XYZ.Site:Mixin.Article.A:
  ui:
    creationDialog:
      elements:
        propertyA1:
          ui:
            label: 'propertyA1'
        propertyA2:
          ui:
            label: 'propertyA2'
        propertyA3:
          ui:
            label: 'propertyA3'
[...]
```

### Possible Solution

Dont move fields in the creation dialog when defining `creationDialog.elements` only for a few of them.
