### ISSUE TITLE
BUG: Neos9 `ReferenceEditor` `createNew` doesnt work

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-ui#3732]
Steps:

add this to `Neos.Demo:Content.BlogPostingList`

```yaml
  properties:
    blogs:
      ui:
        inspector:
          editorOptions:
            createNew:
              path: /<Neos.Neos:Sites>/neosdemo
              type: 'Neos.Demo:Document.Blog'
              titleProperty: 'title'
```

server exception

> Warning: Undefined array key 1 in /Users/marchenryschultz/Code/core/neos-manufacture-90/Packages/Neos/Neos.Neos/Classes/FrontendRouting/NodeAddressFactory.php line 76 - Check the logs for details

reason, we currently wrongly compose the node address in the client. This is an error of this kind, which might exist in other places as well: https://github.com/neos/neos-ui/issues/3731
