### ISSUE TITLE
BUG: NodeTree presets, break expanding collapsed subtree

### ISSUE THREAD

**Issue by MiauzGenau** [neos/neos-ui#3816]
### Description

After using NodeTree filter presets, the default NodeTree does not reset properly and does not allow the expanding of sub-trees, 
which where expanded before the filter usage.

### Steps to Reproduce

1. Add config:
```
Neos:
  Neos:
    userInterface:
      navigateComponent:
        nodeTree:
          presets:
            blog:
              ui:
                label: 'Blog'
                icon: 'icon-folder'
              baseNodeType: 'Neos.Demo:Document.Blog'
```
2. Expand sub-tree in default NodeTree
3. Use filter preset
4. Reset filter
5. Try to expand the sub-tree => No sub-tree items get loaded

#### Expected behavior

Sub-tree items should get loaded.

#### Actual behavior

![Screen Recording 2024-06-25 at 14 17 17(1)](https://github.com/neos/neos-ui/assets/46249106/f8f5b272-e930-4bd5-9cb4-0c262826e819)

### Affected Versions

Neos: 8.3

UI: 8.3
