### ISSUE TITLE
An editor receives sometime unfinished ClientEval options

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-ui#3869]
### Description

Sometimes, the editor receives unfinished options with `ClientEval` strings prefixed.

If you have set the option `hidden`, (which is quite a often used case), the interface is flickering as another value change

### Steps to Reproduce

Create a node type

```yaml
'Foo.Bar:Content.Issue':
  superTypes:
    'Neos.Neos:Content': true
  ui:
    label: Issue
    icon: github
    inspector:
      groups:
        test:
          label: test
          icon: github
  properties:
    inline:
      type: string
      defaultValue: ''
      ui:
        inlineEditable: true
    checkbox:
      type: boolean
      defaultValue: true
      ui:
        label: Label
        inspector:
          group: test
    input:
      type: string
      ui:
        label: Label
        inspector:
          group: test
          hidden: 'ClientEval: !node.properties.checkbox'
```

and this Fusion

```elm
prototype(Foo.Bar:Content.Issue) < prototype(Neos.Neos:ContentComponent) {
    inline = Neos.Neos:Editable {
        property = 'inline'
    }

    renderer = afx`<div>{props.inline}</div>`
}
```

If you enter some text the input field in the inspector get's hidden and appears again

#### Expected behavior

No flickering

#### Actual behavior

https://github.com/user-attachments/assets/e2f4ebdb-28b1-424e-b5e4-70595e4bf7f7

#### Note

If found this because I created an editor and log the options, and sometimes he get the options including `ClientEval`.

In the editor itself I can handle it like this: 

```js
function ClientEvalIsNotFinished(input) {
    if (!input) {
        return false;
    }
    if (typeof input == "string") {
        return input.includes("ClientEval:");
    }

    if (Array.isArray(input)) {
        return input.some((value) => ClientEvalIsNotFinished(value));
    }
    if (isObject(input)) {
        return ClientEvalIsNotFinished(Object.values(input));
    }
    return false;
}

function isObject(input) {
  return input != null && (input.constructor === Object || (!input.constructor && typeof input === 'object'));
}
```

But this will not work for the option `hidden`, which is one of the main use case for `ClientEval`

### Affected Versions

Neos: 8.3.17

UI: 8.3.11
