### ISSUE TITLE
Non-scrollable Neos.Neos/Inspector/Editors/RichTextEditor

### ISSUE THREAD

**Issue by auwaerter** [neos/neos-ui#3906]
### Description

Scrolling within the `Neos.Neos/Inspector/Editors/RichTextEditor` seems not to be possible. The **Discard** and **Apply** button moves below the visible area (even more when re-entering the editor after an apply).

When i click Apply, re-enter into the editor i also can't scroll down using the mouse. I can only enter and use the keyboard arrows or the page down button.

This bug was supposed to be fixed within https://github.com/neos/neos-ui/issues/3664 but probably came back smh.

### Steps to Reproduce

1. Use Google Chrome v131.0.6778.265
1. Create a new page that includes the 'Super.Vendor:Content.Text' NodeType, which contains the 'Neos.Neos/Inspector/Editors/RichTextEditor' using the above properties.
1. Create 1000 words here: https://www.loremipsum.de/
1. Navigate to it and add Text using "Toggle the editor".
1. Apply (you already notice, that you can't scroll up to edit the content or e.g. select some properties)
1. Enter again, to "Toggle the editor" (you can't scroll down, but you can use the arrow up/down key / page down button)

In the mentioned case, i'm using:

```yaml
'Super.Vendor:Content.Text':
  superTypes:
    'Neos.Neos:Content': true
  ui:
    label: 'i18n'
    icon: file-text
    position: 20
    inspector:
      groups:
        settings:
          label: 'Settings'
  properties:
    'text':
      type: 'string'
      ui:
        label: 'i18n'
        reloadIfChanged: true
        inspector:
          group: 'settings'
          editor: 'Neos.Neos/Inspector/Editors/RichTextEditor'
          editorOptions:
            placeholder: '<p>Text</p>'
            autoparagraph: true
            linking:
              anchor: true
              title: true
              relNofollow: true
              targetBlank: true
              download: true
            formatting:
              strong: true
              em: true
              u: true
              sub: true
              sup: true
              del: true
              p: true
              h1: true
              h2: true
              h3: true
              h4: true
              h5: true
              h6: true
              pre: true
              underline: true
              strikethrough: true
              removeFormat: true
              left: true
              right: true
              center: true
              justify: true
              table: true
              ol: false
              ul: false
              a: true
```

#### Expected behavior

1. Scrollbar appears
3. The **Apply** and **Discard** button is fixed

#### Actual behavior
![richtexteditor](https://github.com/user-attachments/assets/dff1c005-7158-4603-b4c8-eede605dc52d)

### Affected Versions

Neos: 8.3.20
UI: 8.3.11

Google Chrome: 132.0.6834.160

**Comment by auwaerter** [comment]
Adding a height with e.g. 0px seems to solve that issue

```css
.zNd9SG_editor {
    color: #000;
    background-color: #fff;
    outline: 0;
    flex-grow: 1;
    padding: 15px;
    overflow: scroll;
    height: 0px;
}
```
