### ISSUE TITLE
Fatal Error in DimensionSwitcher on dimension with multiple values

### ISSUE THREAD

**Issue by frozenstupidity** [neos/neos-ui#755]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

The dimension switcher causes a white page with the following error when the content dimension in this case language contains more than one values.

> TypeError: Cannot read property ‘contains’ of undefined

This seems to be caused by the evaluated eel `${Neos.Ui.ContentDimensions.allowedPresetsByName(documentNode.context.dimensions)}` resulting in the array `['de']` being passed into the function when the values in the dimension configurations are `['de', 'de_DE', 'de_AT']` this ultimately causes the function not to match any of the dimensions and to return an empty array when initializing the allowedPresets prop.

**Comment by frozenstupidity** [comment]
It looks like the following code:

```
$preset = $this->contentDimensionsPresetSource->findPresetByDimensionValues($dimensionName, 
$dimensionValues);
if ($preset !== null) {
    $preselectedDimensionPresets[$dimensionName] = array_shift($dimensionValues);
}
```

may be irrelevant as I think the `documentNode.context.dimensions` evaluates to an array of identifiers, however tests are showing this to cause some other errors, similar to those when switching from English (US) to Dutch in the demo installation so will require more debugging.

**Comment by frozenstupidity** [comment]
It appears as though this issue is not so much an issue with the menu as much as it is the dimension being initialized with the value of Neos.ContentRepository.contentDimensions.language.default which does not match the values of the values of the preset.

**Comment by frozenstupidity** [comment]
This issue appears to be related to issue neos/neos-development-collection#1204 which also identifies issues with the definition of default and defaultPreset in combination with presets.

**Comment by skurfuerst** [comment]
Hey,

thanks for your comments and ideas ❤️ 

I just spent an hour figuring out what is going wrong; and I don't really understand the issue yet. I feel one pain point is that we do not all have the same configuration to debug from – Would you mind adjusting the Neos Demo Site in a way that it exposes the error, and post the Settings.yaml here – so we have the same state?

All the best, and thanks again,
Sebastian

**Comment by frozenstupidity** [comment]
Hi Sebastian,

I have attached the whole demo settings which reproduces the problem., however the root cause of the problem can be narrowed down to 

```yaml

Neos:
  Demo:
    flickr:
      tagStreamUriPattern: 'http://api.flickr.com/services/feeds/photos_public.gne?format=json&nojsoncallback=1&tags=%s'
      userStreamUriPattern: 'http://api.flickr.com/services/feeds/photos_public.gne?format=json&nojsoncallback=1&id=%s'
  Form:
    yamlPersistenceManager:
      savePath: 'resource://Neos.Demo/Private/Form/'
    presets:
      bootstrap:
        title: 'Twitter bootstrap'
        parentPreset: default
        formElementTypes:
          'Neos.Form:Base':
            renderingOptions:
              layoutPathPattern: 'resource://Neos.Demo/Private/Templates/ContactForm/{@type}.html'
          'Neos.Form:FormElement':
            properties:
              elementClassAttribute: form-control
          'Neos.Form:MultiLineText':
            properties:
              elementClassAttribute: form-control
  Neos:
    userInterface:
      editPreviewModes:
        print:
          isEditingMode: false
          isPreviewMode: true
          fusionRenderingPath: print
          title: 'Neos.Demo:Main:editPreviewModes.print'
          position: 200
      translation:
        autoInclude:
          Neos.Demo:
            - Main
            - 'NodeTypes/*'
  ContentRepository:
    contentDimensions:
      language:
        label: 'Neos.Demo:Main:contentDimensions.language'
        icon: icon-language
        default: en_US
        defaultPreset: en_US
        presets:
          all: null
          en_US:
            label: 'English (US)'
            values:
              - en
              - en_US
            uriSegment: en
          en_UK:
            label: 'English (UK)'
            values:
              - en_UK
              - en_US
            uriSegment: uk
          de:
            label: German
            values:
              - de
              - de_DE
              - de_AT
            uriSegment: de
          fr:
            label: French
            values:
              - fr
            uriSegment: fr
          nl:
            label: Dutch
            values:
              - nl
              - de
            uriSegment: nl
          da:
            label: Danish
            values:
              - da
            uriSegment: da
          lv:
            label: Latvian
            values:
              - lv
            uriSegment: lv
```

The problem is caused only on login because the initialization of `documentNode.context.dimensions` is done using the value of `Neos.ContentRepository.contentDimensions.language.default` and not the value of `Neos.ContentRepository.contentDimensions.language.presets[Neos.ContentRepository.contentDimensions.language.defaultPreset].values`, if the url for the admin is called directly e.g. using the url `/neos!?node=/sites/neosdemo@user-marcroberts;language=en,en_US` then the login works, however you will also see issues with the DimensionsMenu rendering.

I hope this helps.

Regards,
Marc

**Comment by dfeyer** [comment]
Ok I did some more testing, this configuration work nicely

```
Neos:

  ContentRepository:

    contentDimensions:
      'language':
        default: 'en'
        defaultPreset: 'en'
        label: 'Language'
        icon: 'icon-language'
        presets:
          en:
            label: 'English'
            values: ['en']
            uriSegment: 'en'
          fr:
            label: 'French'
            values: ['fr', 'en']
            uriSegment: 'fr'
          de:
            label: 'German'
            values: ['de', 'en']
            uriSegment: 'de'
          es:
            label: 'Spanish'
            values: ['es', 'en']
            uriSegment: 'es'
          pt:
            label: 'Portugese'
            values: ['pt', 'en']
            uriSegment: 'pt'
```

But this one break:

```
Neos:

  ContentRepository:

    contentDimensions:
      'language':
        default: 'en'
        defaultPreset: 'en'
        label: 'Language'
        icon: 'icon-language'
        presets:
          en:
            label: 'English'
            values: ['en', 'fr']
            uriSegment: 'en'
          fr:
            label: 'French'
            values: ['fr', 'en']
            uriSegment: 'fr'
          de:
            label: 'German'
            values: ['de', 'en']
            uriSegment: 'de'
          es:
            label: 'Spanish'
            values: ['es', 'en']
            uriSegment: 'es'
          pt:
            label: 'Portugese'
            values: ['pt', 'en']
            uriSegment: 'pt'
```

In this configuration the en preset as a value of ```['en', 'fr']``` and ```ConfigurationContentDimensionPresetSource::findPresetByDimensionValues``` does return nothing because it search for ```['en']``` (the current node dimensions value)
