### ISSUE TITLE
Cannot add element to a container child node element

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#824]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

## Problem

In the new UI, I cannot add elements to a container node which is added as a specific child node of a document. There is no problem if the container node is added to childnode of type content collection.

Works in old UI.
Tested with version: neos/neos-ui (dev-master 479c3f4)

### DocumentNodeType
```
... 
  childNodes:
    map:
      type: 'ContainerType'
```

### ContainerType

```
ContainerType:
  superTypes:
    Neos.Neos:ContentCollection: true
```

**Comment by skurfuerst** [comment]
Hm, can you explain the issue some more? :-)

All the best,
Sebastian

**Comment by dimaip** [comment]
Hmm I can't even see that node in the new UI!
I added this to NodeTypes.yaml:
```
'Neos.Neos:Document':
  ui:
    group: 'general'
    creationDialog:
      elements:
        title:
          type: string
          ui:
            label: 'Node title'
            editor: 'Neos.Neos/Inspector/Editors/TextFieldEditor'
          validation:
            'Neos.Neos/Validation/NotEmptyValidator': []
  options:
    nodeCreationHandlers:
      documentTitle:
        nodeCreationHandler: 'Neos\Neos\Ui\NodeCreationHandler\DocumentTitleNodeCreationHandler'
  childNodes:
    test:
      type: 'Neos.Neos.Ui:Container'

'Neos.Neos.Ui:Container':
  ui:
    label: 'Demo'
  superTypes:
    Neos.Neos:ContentCollection: true
    Neos.Neos:Content: true
```
But the `test` child node is not even visible in the new UI (in old one it is).
