### ISSUE TITLE
Text aligning options

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#829]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

In the old UI, aloha provided options to align text:
```
  properties:
    text:
      ui:
        aloha:
          alignment:
            'left': TRUE
            'center': TRUE
            'right': TRUE
            'justify': TRUE
```

These options seem to be missing for the new UI.

Also support "strikethrough" etc.

Needed by one of the Core Feature sponsors.

**Comment by grebaldi** [comment]
Hi @daniellienert,

I addressed this in #1005, but the PR only handles the alignment options.

All other formatting options should be working imho. `strikethrough` should be available via:

```yaml
  properties:
    text:
      ui:
        aloha:
          'format':
            'del': TRUE
```

Can you confirm?
